#!/usr/bin/env python3
"""
NGIMU XIO to CSV Converter - GUI v1.0
XIO 파일 포맷: SLIP 프레임 안에 OSC 번들/메시지가 담긴 바이너리
"""

import csv
import struct
import os
import sys
import threading
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from pathlib import Path
from collections import defaultdict

YONGBEE_ICON_B64 = (
    "AAABAAUADRAAAAAAIACRAgAAVgAAABogAAAAACAAyAcAAOcCAAAnMAAAAAAgAGUOAACvCgAANUAAAAAA"
    "IAAhFgAAFBkAAGmAAAAAACAA5zsAADUvAACJUE5HDQoaCgAAAA1JSERSAAAADQAAABAIBgAAAM2j9TkA"
    "AAJYSURBVHicdZJPa1RXHIafc869c+beO3MnM3EmiSapFq1dBMFSuxG6KIh+CcGPJvgJCkI3XXTRRUqD"
    "KaTRoIlxoUbrMJn/uXPvOefnIiiC9Fm+8Czel1ctSie12PAJEVCKr/gyjw5enTIvHOsrDVY7KVGked0/"
    "48nzAeN5RTOJuHmtw2Yv/SyqsvKyd9hn4YSzoqLdtOwejbi6ntNdqvPv8ZC94yF3f1zj9lb3XBQRGY4L"
    "BuOC2Fr+edGn17Ksti1GK9KkxsHrKb8/eceDu9+y2UvRIsJSXqdyQoTnlx8ucjr3/P1ixGDmGE8XdBua"
    "1VbMzkEfAA3n7ZY7GTsHH1ASuHdrje83c7afDdh9NSFr1LnctbwfzHFe0J8WmZ5V/HzzEtt7J1QusHVl"
    "ift3riBBePjbEZtrLZLEMpqVaADnhcwaWo0a333T5s/dNwAk1nDjcpOyrNhYaWA0VC6cSyJCnsWIwPpK"
    "kyyJ2dl/B8Cvf7ykLCqM0TgvREajRUBrRRxpALwXftpa5aQ/Y/+wTye3WCPMF54gQjONQf6HEII8erwv"
    "ZeXl5MNEjk+m8vLtRERE1F/P+jKaVjSziGLhcUGwkQaluNCyLOcWYzRF6dEK2o2YaDQtWW5ZkprBRprh"
    "rCStR0zmFYdvJrw/LZAgGKNQSnHregc9KRwXlxOO3k7Js5jbW11aWUy9pkmtoaw8glCvGbK6wRhFNJ5V"
    "bD/ts9FLGU5L/jstyLOYRhIzmjlqsSFIoHQB5xXeC9H1jZx54ai84JxQVp4gYLRivZfSbtTwQfBBCOH8"
    "CB8BoM07+jjXpxcAAAAASUVORK5CYIKJUE5HDQoaCgAAAA1JSERSAAAAGgAAACAIBgAAAAyraAUAAAeP"
    "SURBVHicnZbbb1xXFcZ/e5/b3O2ZzDh2bMdOazttbEPTpG3aFKlpKagS5SIQUIHoW/kDeIZXnkHisTwg"
    "oDygIrX0IlQKTdqkt5TGaR0nqR3H8XXGnvHc58w5Z28ezszUbmhBLGl0Rmfvvb69zvetb2+htdZag0Yj"
    "hEDwxdGduzcEAvFfFgq37WvbMvYkCpOIz6zsvP7ChFp//rh5fWWXjz7ZYXYyy8hAnFTC6Q0qrenW2E2w"
    "XXHZKrWoNXwAEjGLXJ/NQH8EIT4fTASB0q+ev4kXaCp1l+FsnDuGU+QyMeJRqzexXPc4O5fnykqZRisg"
    "UBopwLENorbB0IEYD05nGRuIoeE2CoTWWjdaPu9e3mDyyAHeXyiAUphC05dwGB1MooTBK+9tUKq4HEw7"
    "DGViRByDYsVlbbtBo+UjhUBIwemZHA/P5G6rTCiltBCCxVu7rOWrPHR8hLfntymWWwylHYRWXF4ska+0"
    "OXn3AI/cO4SxJ8FmscVbHxe4vlrBMiVNN+DM8UFOT2f3gQmttVZaI4Xg3AdrJGIWx+8a4MpKmYvXiqST"
    "Dicn+wm8gOWNCitbNcYP9XF0LE069SmfF+a3+eelLSxDEgSapx4b5/BArAcmdEdmSoXy/vNr13hgdpDD"
    "gykaLZ9/fLjJwq0qM0f6eWg6h9SKheUSG9t1mq7PnaP93H0kQ9Qxubxc5qULa2itGRtM8NSZMRAhXz2g"
    "LnK51ub5v1/j+1872hPD0kaVl99Zp1L3OHUsx4PTWaK2Qb7Y4NK1AtVGGykEsxNZ5lfrXFmpAJofPTbO"
    "cLZTVReoK2cpBNdvlnh/founnrgLP9CYhsDzFW/MbfHWR9tELMmJqQwPHMuRjJoAXF0ucX2lyG61zfpu"
    "GyUMTs8e5CuzubBN9gJ1/5XqHn94eYGZ8RRn7h/DDxSmIQG4uVXntYsb3NiscyBl86Uj/RyfypBJfsrX"
    "cy/P8/7VIo+cuoMnHzz0qRj2AgkBL72zzj0Taf52bpH7ZgaZmcj2OBQC2r7izct53ru6Q9NV9CcsZo/0"
    "cc9EhrmFLa6ulFF2BKU0z3xjAtuUyH1NJaDR8nEsyfCBKN99fIoX3likWG4hpehtxjYljx4f5IdnQmXV"
    "mj7vXS3xm+evUKy0ePqbx2h7AU03oN4MHUTurQZgs9RiNBcSmIrbfOuRCZ79y2W01mite32hNYwdjPPj"
    "r45zYjKNYQgCpXn4+DBR2yAZtWj7CtdT+4G60fYVQ5koQkCgNNN3HmDicJrfvTiPlGGybvVBoLAtg6Qt"
    "qDfaWIZAqdDboxGDQCn84DNAQoSqMw1JMhYqyegk/s6jE+RLDc5evIUhw2QAUkq0hjf/tYbnBQg0EcdA"
    "AIYQ6D2nyb6K2p4iHjERQvROHNlZ8NPvfZkX3lhiZaPSq0wIKFVaLK2WCXwfKSBihZv0Ao0hRU+t+4A0"
    "0BcPJ3btLLR+TSpu8/ST0/z6jx/gegHdnZy/tE6l3qbtepiGxHFMlNI02wGmIbFMcTuQKQW2eRttvQpm"
    "J7PcNzPEr35/EcMQ+IFi8dYuSimKu00SERMpBXU3oNH0sS1J1DFvB7JM2Sv1s9Hl5gdfP0q14fHKmzco"
    "lJqcOHaQnz9zisJOjbbbBqDa8NituUweShBzDLQGqXXnHvA//CA035/95CR/PbfEn15dYPJwmtnJLL94"
    "5hRD2TgANzZq5PojPHrvYLhOAPr/jEtX8/qXz77zH8cuzBf0btXd907sVFxdb/mYhgxlKyAIQpl3GzS0"
    "JoHWOmwBKTFMge9rLCuchw65VFqjFDiWpO0r+mImEdvAfOujAjc2arieIuoYBIEmFbfYqbg4psTruHfX"
    "xRMxk7VCk6nRFI+fHKLVVjiWJFAaPwg3JiW4vsLzFZWGFwJJAd8+PczZuTynjmUBmBhO8fZ8AduSlGse"
    "usPN5EiSsYMJfvvKIhFbcnOzxvmPC5yYyhB3DM7OFbjjUIJYxGR+ucz4YJzTM7mwTZ57fVnfOZTgUDaK"
    "IcG2DOaWdpkaSfZ65ZP1KuODCdpeQLHaRgjBrXyDdNImk3JY226gAs1AJsLkcJJzcwUmR5JkUjaWFGRS"
    "DlIKwcKtCsPZGMWqx07Z5dxcnlK1TTRikkk5DPRHSMUsljfrbJddak0P0xAYUnDlZoV4xKQvYbG0Xie/"
    "62JZgmurVXbKLkbXGSxTsllsUqy4rBbqSCl6clZKk99tMT6Y6FiOYOZIP8PZGKozJ52waHuKasMjYkvM"
    "zhXJtmQHRPesDD/Q1Fs+hV2XZMzkvrsyZFI2jZbPjY0agdJU6h6jAzFWC42ePQVKcXQ0hdbhBXNqJMlQ"
    "OoLna46NpTiYdvCDDlB394YhKNc8FtdqPHH/MBs7TbbLLqVqm/XtBksbNRIRk4emc9SaoYGm4jYvXFjD"
    "MiVTIyle+2CL1z/ME3NMXjy/zrnL2z2nES9eWNULKxUG0xFKtdBCRgdirBWaRB0D1wuwTYO2Hz7TSYut"
    "kkuu3+H0zAB1NyDuGCilcX2FIcPjXinwgrCPBvojiHKtrV0vvEsbMkTvJlX7GjZ8BoHGMET4zUX47btH"
    "hhAhJRqQAgIVngaOZfBvuTQ1ty0+OG0AAAAASUVORK5CYIKJUE5HDQoaCgAAAA1JSERSAAAAJwAAADAI"
    "BgAAAJJwYxYAAA4sSURBVHiczZlZbFzXecd/59x7Z+UMhxwOSVHcRC3WWsqWLUuyE1u149RuUDR2Y6dJ"
    "2qRG0hQNigJukRYFWqMPLdoG6UsLOE1hIEhbpEWaekvbxLZiu7Jl7YtlUaRES6LEfThDzj5zl3P6cGeG"
    "pEXZTtKHHoDE5b1n+Z9v/X8fhdZa8/90mI0HpTVCCMTPueFaVxU/46ay5nj+Qx2Yxgf60wJqLBHi5h/q"
    "+/60OjIXc1Ve+p+r7NmWYrCnlfbWEKK+o9IaAc2/bwJV/9X4XLU9ihWXSs3D0xpTCsIhk5aQSdCSNNSi"
    "9UeTptndEaUrGeFHb1+nf10cz3XZtiHJjo1JomGrOdEHKpYl0ThAwEy2wrtXc0xnKhTKDjVHobRGCkHQ"
    "ksQiFp2JEJvWx9jU04IQHw2gUEprIeD5196jtzvOUqnG+bE0rVGL/nVxupIRNvYmiISa5olSGikFVdvj"
    "2GiGM5cXqdRcGnYhhG8mUvqne0o31wyti7Fve5K+VAQNH2jjTXALixX+8/AVHvvEFibmy4xcXaQtYlCp"
    "2EzOFehMRrlrRzd9XTGEgIW8zYtHJpnJlH17FRAKmMQiJpYhqdoe+bKL43qYhsA0JJ7SOK7CsiQHtqc4"
    "sKPjAwEK7Q+EEJy9lGZkPMPnHtnK5akCFydyRMMmvckQ8wtFJmbyeAq6khEyZU226KKUJhkPsLk3Rn8q"
    "QiIWwDQktuuRydmMTxe4cDVHoeIQtCQCgacUjqfZtz3FweFOH8gaCEUjzjXE/vxP3iMSNnho/yDlqsvh"
    "8/OMTxUY3tTO8FCCStXmzGiac5cWQEp6uuI8eFcP3e2R5qbvt6d0rsbr5+YZn8pjGbLuYJqq7fHgnnXc"
    "vTW5pg2KlUFYaQ0a/uEH73Dv7h52bU4BMDFX5JWTs+RKNnu2JNm3I0XIkoxezXBlMsfkfBGN4I6tndy+"
    "NYVpyOYBnqcxDIHSmuNjixw+Nwf4gmg4zRP3D9CbitwEcBW4xsf0YoVnnzvPbz+2i7Z4GCHA8RRvnJvj"
    "xGgGy5Ac2Jli9+Z2IgGDmu1yamSe4+/OYpqSjX0Jhnpb2dyXaDpFw3TOjC/x6ukZBBopJVXbZWhdjMfv"
    "62/OXRNcQ3pSCM6MzvPqsQn+8DfvRGkw6gunF8q8fGqWK9MFOlpDbB+Mc/e2DmL1sDOdLnL5+iKjV7Nk"
    "cjV2DCU5sLuHVFu4ecaJsSyvnJwmYBkIIbBdj1/7eD+b18dWSe8mcCvt719/PIZSis89vA1PaaSgvpni"
    "6MgCJ8YyFEouXe1Bdg4m2DHYSns82Nxn/MYSR9+ZIZOrEo8G6OuOMbwlRaotzKGz8xwbmSdoGVRtj+0D"
    "CT59b++Hg2sAFAL+8tnj3L+nl3tuX19/txyIp9JlDp2dZWK2hJSCRDTArqFWdm9qIx4JNPeq2S7jN5Y4"
    "eWGO8RtLDK5vZfvGDs5dK+B4mprtIaXgyYeHSEQDTYC3BNewkWyuyl9/5wRfe3yY/nXx5sLG95rjcXIs"
    "y/HRBUpVDymhPRZk20Cc3UNttLYEVu2bK1Q5PZrmyuQSk/MlHCT9PQlKNcUDd3TzC0OJjwCu/itbdPjx"
    "2xOMjM3yp1/dh1W3E8HqkHF9vsTrZ+eYzlTql4PWqMUdm9vYPpggHrFuOiNfrPHCa+O89MYVHrh3C1s2"
    "tHFwuPOjSM6f8G+vTdDdEWV+JsPV6Rxf/9JePKWbDrJSyrarODmW4ciFNK7n263radpbLHZsSLBnSzuR"
    "oNmcf2VyiX/8wXn6etupKoNUIsgXPrGhmTHkBwErVBwWizbbelv4zEO3sVio8cLr4xhSoNTynYQQaA0B"
    "U3JgR4rP3NdPbyqC52kCpqRQcXnj3Dz//MpVjl1coFzzOHR8gr//3hn2395LKBqhansUyi7VmtfU3Nre"
    "qkEKOH91ifGpYt2LNNlcjae++Tpf/9Kd7NjY0fTqtS7muIpjFxd4e2QBT2kCloHteEgh0J5HJr3IU7+x"
    "h5ZoiGdeGGvSsi9+cohUaxCtbyG5xnE30mV2Drb6gBUkEyG+9sRuvvndUyzmqwgpeP/dGnTIMiX37urk"
    "swcH6EtFsG0Py5QEgybpxTK//ktb6U5GkUKTaAmilMZTmnLVbe61NjjhE0fHVQx0+TnTMHxV7t3Zzf7h"
    "Hr7xnROIupTXWt+QYl9nlCcODrBzME7V9kCDZQjCIQOtIRwwaQkZKO0nANtVdbXqm8E1BJHJ10glQgQs"
    "o/lO1m3tK4/uouZ4fPvfz2FIgbcWwjpIT2mfpVRr2LbP+ZRShANmk8aHQ76ToH1z+EDJARQqLus7wje9"
    "b9jGHz+5l0PHb/Dm6cmbHGTlMKTAdjxOXZhDK1WvNzTh4DJ5tczVnv+h4Co1RTIWbEpgpTSU0qTaIvzB"
    "F+/kG989yfR8EbmG/TUKpfcmc9yYK4LSeEoh0ARXgBO6HldXXH5NcA0GErQk0RXUfOVoqHfvjm4+9fFN"
    "PP3MEWq2e3OFVX8+N5bGcTxs28H1FIYUhAJGc5rtNQopVtGtNSVnO4q2WMD3vDXhgagD/PKndxIMmPzt"
    "P51CCrGqrJRS4Hma0WuLWJZP+e2aS8gyCFrL4Kq2B3VSEairWNwKHEBLyGhOWhMcy3Xp07+zn7fPzfDc"
    "octN+2vY4LvjacauZolGLOyaS6XqEA2bTVvxlKZc8xAIDLFSouLWcS5o3RL38ry6pFJtYf7oyb088/2z"
    "jLy30GS5AMcvzJLNV8gXahhSUC7XiEeXyUC55lKuur5KTUE4uCzRNREEAxLL/HBw4JeASmnu2d3Dow/c"
    "xp/83Zvkiz6QXKFGperyN0/dh+N6zC4UsW13FbhixaXmeCiliUUsoiGrfvFbgDOk5FZV/lqjIcGvPLaL"
    "9V0xnn7mLYQQnLs0T1s8xPDmDv7i9+6lNRZkdHx+FbjFgo3tKECzd2sS0xDLcfUjI/hAcL4pGFLwZ1/d"
    "z7lLC3zvvy9ybabAnm1dKK3Z3J/gr37/Y/SkoljG8sXnFquUqw533ZZk14bEKhqG/j8cnqe01lq/eXZK"
    "7/vCv+g//9YR7SmllVr+Npct6el0sTn/2z+8rF9464Z2PX/eyrF2IPsZh5R+wXzPcA+Pf3IrXclIM7w0"
    "2Etn23J9mynYbOyJcf9w503sBt5fGnLr0LHy262eod4OA0oVB8dVtESsVZP840STXARM6YefujpNudxj"
    "Ee9eW9KnLy9iGXK58VJnsQ0aY5nST+KeRsq6A9TjmFFnu57yiWVDght74wQtA6VUE/RNFT0CXQ/zQoDt"
    "aFojBkPromjAzORrzGXKxCImmbyNEIL2mEWh7BIOmnS0Brg+V6DmKJKxABXbo1zzaGuxcDxNrmTTlQiR"
    "aAlwbTZPzdFEQwa/eHsnsbCJp0BKMA3/EkqtKP2ET7kaAd1xFemlah04mJ6n2TWU4ODt3Tz7X+PEoxaP"
    "3zfAkQtphje2kWgJcGWmyHOHr/P4wQFmsxW+/8Z1Hv1YP+NTBcYm83z+gQ2EgwYXJ5Z48e0pApaBFPDy"
    "qVnSS1WEENw33EnQkrx8chZD+uTh7u0djN0osFS08TzNlr4YQ+tiTclKwxBcmy0RMCW9qQibelpQWjPY"
    "HSXREiBbqDG0roXb+uJ4nmZzb5yWsNmUxr5tHYSDhl9rDCRY1x7GdhQamEyXMQxJuepxbGSBfMlhOlOu"
    "E0twXM1kutxsNqpGyVcfZsCQzC1WmV+scOeWdgKmZHqhTEdriDOXs7x+do4v//ImtvTGsV1FwJQMdEWp"
    "1DwiIZP+zggnRjMcGUnzu7+yhf6uKHOLNV8thuBX71lP1Vb88OgUNcejPxXh8w9uAGCpZBOwDD57sJ+W"
    "kIntKmaylWVw1NnqpckC9+7qRCnN+Ws5epIRxqeLLORrTMyV6GwL4Xr+rTb1xFDaTzemKRmfLgDwzpVF"
    "Fgs2hiGa9Gn0RoFCyaEvFSUcNClUXMYmCxhSkGixUEpxabJANGjSFrNWlZwS/PpgfLqI0pp82SG9VMUw"
    "/GreNAzKNd/lpRQUKw5DPS0kogFMQyAQOK7HI3evZ8dggmQ84NeldSM//E6aoyMLBEyJaQiyeZuXjkzx"
    "oxMzfmPb0xw6Pct/vHmD63MlrBV8ztQaLEMyv1RlqWgzv1Qlk6v5rdJ6UA1aEsdTmFJwearA0LoW2uNB"
    "0rkaQvi5uFh2CAUMoiGzmRu1hkf2dhMMmBw6PUvAEnQnQzx0Zw9S+MzHMASf2r+eWNgiEjQorVV9KaWx"
    "HUXN9ihU/HZqf1eUaMigLxUhV7SRAjJ5m+tzJQDyZQfPUwx0RfnJ2TnKNRe5gqEKAd3tYTZ0R326VPNo"
    "CZn0doTpSYab2hjsitLbESYRNVeR1RXpS9SNWFKqukxnKuzd2kFfZ4T2eJCTl7K0x4JorXlvusCuoTaK"
    "FZeZbIV92zvo64wSCZq4jcCFH7RfOzvfbFQnohZnL2d5/q1JlNJs7W/FcRUvHpnClIL1qQj9ncvpTa5k"
    "tEL6AVNrODqSQQhNXyrKbLbCxYkcQUtiGZIrMyV0/Z8gRy9mMAzfg23Hb2U1Wv3J1hAz2QrzS1UO7EzR"
    "1RYmHLKYX6oxu1jD9TTJeJBswWY6W6VQdliZYsXh8/P61VOzWKZgfTKM7SrmlmqgfbV2t4UYvZ4nV3LY"
    "sC5KruSQydts6I5SqrrMZqts7o3RGrWYyVTwlCZfdvmth4cIWSaO0hgCwgEDx1PYjkZIP5w1skbDBDzl"
    "Z5yh7hb/3eXJvL44kccy/S6REL4jUE8nSvl1pZQCx1VIITCM5WfT8NdpTTM3W4Yg1ebbVMOCGs3IlSR2"
    "VRdTgOMokvEAA11R/9utWmA/71BKL7cqxAoWs+K0pu+scCBDLE/+X0u2jLUQ7hfYAAAAAElFTkSuQmCC"
    "iVBORw0KGgoAAAANSUhEUgAAADUAAABACAYAAAC6CT8CAAAV6ElEQVR4nN2aeZBdx3Xef9333rdvs++D"
    "wcwAGIBYiJULSNoiFZGMZYeSY8kq2iVbscupWIqSlJeUq1zlpORUUmUnURLHVpKKnMQshbJsKYoZOlTR"
    "ZEiQIEESxL4NMJgds7yZeft27+3OH/e9O28wADFQJLkqXTUzb97t291fn9PnfOecFlprzf9nTf51L+CH"
    "0XxQSml+VDLTTT8/jGbajkIIMI11oXkaKRDiBzNJY7Ma491pWN34Je78/H6a6SrFn37vOl1tYQ7v7iQV"
    "D2HI9WGV1gghvq+JtPaANMA4rsJ2Na6r0fVxDUNgmRJTbkTTePf7AhUKmOze3spXXzjN5YlVWhIhejui"
    "jA6kGOpNIOsjK63rc95bgs1gihWH+ZUyi2tVVnIV8iWHctVFA1JAKGASj5i0xAO0JYJ0pYK0JYMI8f1r"
    "jFBKaSEEL781yUK6yGBfivPjy5RKNWIRiyN7uti/o4NYxNqwaPB2ehMgvA23XcXFqRznJzKsZCtUbbUO"
    "tqkvunG2NJZpEAtbDHZG2T+cpK89vGGTtgxKa62V1iil+fr/uMiBXZ30dMW5NpVhai5DNl8hZBm0t4TZ"
    "1ptkx0CKlkTQH8CTYF2GwoM0ky7z3uUVxudygMaU0tt5ms4XjYWKOjiNxjNYrtJEwxYPDKV4cCRJWyLo"
    "q+uWQTV2Ip0p8/XvXOSzT+8kFg9xaTLLSrZCe8zCdRyuTa0xny7S0x7j0QM97Bpq2WBglNJ8cH2Ndy6l"
    "KZZtLFOitXeWwDNGjf6Oq/zvDSl8NW8gdpVGuZrWZIjH93WyezC+ZWCi4XwbL5y+vMT3Tk7yD37uEEJI"
    "Pry+ytWZHH3tEcYGE9SqNu9dXODyxCqJeJBdQy2M9qcY7k9yYbrAK6fmcB0X05Q4CqIhg66WML3tYTqT"
    "IaIhAyEExarDcqbK7HKJxdUypaqLIUFK4albHZzjKizT4GMHuzg40rIlVRTNjEJpjRSCv3hjgptzWb70"
    "uYMALGUqnLy4zNRikdG+BA/tbicaklybXOPyzRWmFwrUbJdgOERXRxwtJIWyw0hvjN2DCTpTQUIB444L"
    "qDmKhdUK5yYyXJ7KopTCrEsYPABKaTSCJw92cWRn6z0lJm6nSUp5L/zrFz5k52CSn3hiuP5Ec/ZGhjfO"
    "LVKuuhwYaeWhPe2kohaVqs3Za2neOXeLxdUSqWSY0cEWHtvfTWdrxB/bVbp+ltYX1PiotObSVJ63Ly6z"
    "mqtgGdJ3zg1gUkqeO97PSG/sIyW2CVSjcyZf5ff+6/s897ERjuzpxlUKQ0rW8lXeu7rCB1dXCQYNdvUn"
    "2Ls9xbauKAAzC3kuT6wys5gjnakQDBjs3dHB0T2dJGO3GxjgNiOzmq/x9sU0FyczG/ylEOA4itZkiL/9"
    "xCAtMcu3tPcE1ZhQCsGVm2v80bfO8FtfOEZnW7S+W94w12ZzvHp6geVMlUjIZGd/jGNj7XS3hn2Jzy8X"
    "OHttmbfOzFMsOxze3ckjB3oZ7I4TbFLHhnY03ITjal47s8wH15Y3GCIpoFxzObyzjWeO9txVWncE1Qzs"
    "u6/f4MzVJX7980cIBc367ngOMVOo8v7VVc7fzJArObTGA4z2xdnZH2eoK4pRX5DtuFwYT/PBlSVWMhUs"
    "S9LZGmHvSDsPDLdiWUZdSzRKgxQCpTVvnF/mvStpDCF8VdRaYxiSz/zYIP0dkTsCuyuoxg5KKfhXf3Ia"
    "KeDLzx/yv2se7OZCgf9zdpGZ5TKGFESDBgOdUY7samWgM7pBRfLFKhNzOc5eXeLctTQIwcP7ejh+sJee"
    "9qjfT2vPX73ywSJnxlcIBgx/zkrN5YHtLTz3aN/9g2o8KZRq/M7XTvI3HhrkmePb14HVOwkhKJRt3rmU"
    "5tJUlmLFBSAcMBgbTLB7W5LethCWudECZnIVTl1c4N3zC5SqDn0dMXYOtbB7qJWB7jgAlZrixdenmE8X"
    "CVgGaE+LApbB8x8foj0R3ATsI0E1dkwIwcRcln/6tZP82s8fZu+ODl89G+C9j5qpxSJvXVhmarGEFAKt"
    "NaGgybbOCAdGUwx1xzz1ajqfALOLeS5NrHB+PM3MYoG2VIhH9vfx8L5uyo7mm69PUSjaCOE566rt8uSh"
    "bh7e3X7/oGBdDf/3ySn+9JWr/IsvP05bKrzBXzTzwXLN5d1Lac5OrFGpukjpHf6AJRkbiLNvuIXetjCm"
    "IX0j0byom3NZ3jw9y7nxNFIK9oy04woDW0mEISlXHAplm8GuKM8/NbTBSm4ZVDOwP3jxLNO3snzli8cx"
    "DbnJCTYDnVkq8falZSbmC/W+ULNdIiGTwc4I+4dbGOmNIeoSVVpjyHVrV6k6XJ1c49z4MjdmMixlKrSm"
    "oowMtYGQ5MsOP/uxQTpToQ3S2jIoDWTyNeZXK/z7F95j/452fuVnDmxSo0Zf6pNUbZf3rq7ywbVVylUH"
    "y/Sk47gay5Ts6ItxaGcrPa2e5KhbQGDDuPlijeszGV56c4ITH87xiePDdHW3sncowYHb6NOWchQNLnZl"
    "OsdrZxb51c8d4sSZeV4+MYGU3vlobg0GrrUmaBk8treDn358gF0DCWzHC0GClkeFLk5m+bM3ZviLd+a4"
    "OpPD1d4mibpZV1rjuIp4NEB/V4xS2WbnUCuJZIy55RLpbHXTercEStSJ5aXpLGFLsmd7C7/86f38uxfP"
    "cHMuc0dg3nvr562/I8JPPtLHUwe7CVqSqq2QQhMKGtQcxeWpHP/z7Vm+fWKGmaUium6IpBCYhuT8+DK/"
    "+s9exbJMnv3xMfJVRc1xWcnX/DX6897b+nkvzCyX+O+vTfHco/3s6PfM7de+dY63zszyb37zSZLxkG/e"
    "7zzO+rP5dIlTV1cYn82jtMYyDDReTGc7mlBQMtobZ2wwQV9bmL986yZ//up1furHRxjb0cVfnppHClAa"
    "WuIBPv+JYYJWE/PYiqQAJuYLtMYDDPfEAM9w/NKn99GajPCV//AOHsm5e4ZoXWqa3vYIn3y4j6eP9hAN"
    "mpRrricZKQgGJI6jOX8zwysfLPDVb57n2391nb///CE++/QujHqsZUiJFIJS2aFYcXwBbAmUqA8yuVhk"
    "3/YUhuGxCer+4rf+zjHGZ7J8/TsXPL90BzW8HZzWYBiS/cMtfOZj29izLQ5a4NTPm5SCoGVgO4rphQJf"
    "+txBHtrbjdaa9mSQcMCoGygvdClXnQ1zfCSoBvKltQqOUuzZlvCBNhxrZ2uE3/m7j/DfXrrMX707hZQC"
    "957APGOiNXSmQvzUowM8+1APLfEAbj0aBlAKYmGT/q6Yr76JiEU4aPhpBFdpyjW1Yfwtqd9MukxHMkQs"
    "bG1IeIo6Mzg41snzP7GHf/knH3Bz1gsZ7mQ47gROa499PzCU4lOPDRALGV7cJQSuUgg8C9pQ32DAIBI0"
    "UXWTrLUnra2Dqp/5lWyV0d74Hbs0LN8X/tYD7N/ZyW//wVvkijWEFGzFBfrJFw3aVaRXCsh6ntFxFIYQ"
    "hIIm4AEwpKiDaixP49wPKAHYjgIBg53hpkXcvjCP5vyjnz9Mueby+//lPYSGLWCqL0sjBFydWmNuIYeU"
    "+PkJQ0LQ2kiEA5bwLZIGXLVFUI0FrRVqREMWsbB1t65+uN2eCvPbv/IIb344zx9/98Jd/dem9+t/z42n"
    "qdVcbNtBSoFtu1729jZQ98oo3fNMreRsWmIeoI/a+QaAB3d28Pc++yB/9K1zvHVm7p7APD8oSGfKXLm5"
    "5lm0qoMUgprtEAoYvlFZf6kJIGwitPcEVam5dLUE79XNB6a15tNPjfLMY9v55//5FDdm6ozjLjvSOHcX"
    "b6yQLVQxpKBcsRFSUKu5hBvnqQmJrVRTckJgGhsleVdQDZUKBAxSsYD/3b2bR23+4fOHiUeDfOU/nqRQ"
    "qtVdwJ3nAbh4fcVPpJRLVbTW1Gou8Ua6W69by0pN+c7eq9jch6RsVxEPmwTMrdfmhPAi02QswD/+wjGm"
    "5vN89YXTKK03WcOG6q3lKlybzniRrRBUKjaO4+K6ikQ00MAEgKMUlZrrnSsNQgpCgY3r+8jVukoTCd5/"
    "sbGRONm/o50v/9wRvvPadb7x8uVN56sB8sSHc0zfyhG0DLTWOI5LreqgtCZR15JGq1RdyjW3zv00lhSE"
    "rC2qH3jqF7wPKW0CpjQ/+cR2PvXUTv7wm2c5deHWBmANdTp5dp7ltSKZXBnD8EKSStVGoEnFNp7nQsWh"
    "Wo+mdT1XEQreByjLlITvki7eShNCIKTgiz/7IGPb2/knf/g2k/NZj0q5HmuYupXFdjW/+YWHWMtVWFwu"
    "YEhBqWQjgWR8I6hswabmKKTwKFI4aBCpg9pSkBgwJYaxJetwF1CglSYRDfBrnz9Cqar4vT9+j2LZ9hfw"
    "1odzbO9L8snHt/Prv3CUquNwazlPpVxF4JV0mlumUENphRAa11GM9MQwDbnBCH00oxBiyzWhu7WGOR8b"
    "auE3fvEopy4u8m+/cRrw1Pv9S4s8eqAHpTVPHhvgd7/4GIlYkEvjS+C6xOuGouGK0rkqAi/X0dMe4fCu"
    "1s1z/j+teKvA6ufr2eNDfObpMV546TIvvXGD+eUCSsPekXa/z8GxTn73S4/TmgxRKNd8SQkhsB3FSq6G"
    "0pqQZfDxwz0kIladwa/PZ/4oQHmL8ozCL//0Pq5NrfK1PzvHwbEuHjnQi1lPxjTClqHeOF/50nHePntr"
    "wxir+RrLmQrxkMknjvYx2Bnx3UJz+5FdDhFCoNEkowF+4xeOorXgxOlZjj/YV+/g/THqVm3nYAvPPzvm"
    "p7gBbi4WEcDffHiAscHEJgk1mglsKUT4QTSBx7xHB1L80qf38cbpOfo6o/VsVTPj8M5hM1NwlaZUdvnk"
    "I32M9sX8JOidKvhbzvv9oJvjKBZXS/R1xrb4hqZYcYmG7n1iRLZo68nF4oa8uP+wjr6RUfKTK3rz87v9"
    "f/s73gPPBxpC4N7Hnoq6BP1MLOAoSEUM/3oCgLmcqfDSO3P+rLJxPUCDchWiXjm3XYVWXm3IMDze1QjO"
    "DCmhUZvV2h/DVRrXVQghsIz172JhiycPd2OZEtlU6PE3w//V1LS3OeZtpVVdUyysVTaC0kDQhPZkGKU0"
    "K7kqroJwQNIaj1CpOWQKNrv6Y6TiAaYXiyxnqxhC0NES9GKhXBWtoDVuEbIkK/kaNVuRilgM98Yo11wm"
    "bhXqLMKLXHf0RLDMRj4C0IKmNLpfH67j8WOm5u8bG3njVmEDflPXk/LPHuslFjb58zdnGJ/Lc3RXJ4/v"
    "7+Tdy2lcpXn0gU5MQ5Ar2vyvU3NM3irw9LE+UjGLb7w6yVy6zDN7etnRF+M/vXyDcNDkueP9dLeGUVpz"
    "bmKNV08v4DoNiQjeH1/lxmyBgCVwFXS3hTm+p42pxSLvXlklYApAULMV+0eSKC04P5EhaDUAwoOjLRhS"
    "bkiWmoYUFCoOy9kKHakUfR1hJhcK7N6WwJQS05QcGUn5ligRtXh8Xyfz6TKW4SVBtvfEmFwoEgxIQkET"
    "ATy8u82v/0ohODDSwvhsnivTubqaC5ZWK1yZzhIJWziuy9WZHEOdEUpVlyvTWQKWRGgoVV362sNoAVem"
    "M17OQoBtK4Z7Y6SiG4vaZuP8XJrMsmdbioH2KH0dRTpTIVZyVZIRi6BlMpcuMbtcYt9wir72CNu6otQc"
    "hQZ2DyY5eTFdr2YokrEAI71xlNKcubFGImIx2hdnR1/cB1UPh2hPBXnmWB+ZYo1XTs0zly6RigcIWpLj"
    "ezuJhU0qtmK4O8bl6Swt8SCPPtCBlJ6kelrD5Ms2zffcTKW96zVz6TK5Yo3+zgiHd7YipfQmiAXQWvP6"
    "2QXGZwsIAcfG2ulqDfmHuqslRFdLCMf18uGt8SDxiMWN+TwvvztHT1uY0b44PW3h+tUezyIopQkFDEZ6"
    "okCUkxeWqTnr1vDBkSTxyHo8de6mIhw0OdrE9xxXkSnUNvgpiQbDEJSqLlOLJYKWwZ5tKVylmV4qkopZ"
    "rOZrLK5WsQzJjXnvUCajgXWqLwXbuqNedAu0xD2+dvNWARBUaop3L6e5MV/wI9bGhtiOYq1gM7lYxHE1"
    "fR1hP95aWKuynK1ya7WM43pVENtRzK+WWcxUWMpWsR29yVCajcG1huvzefYOpzCkIJ2tkM5VCYdMVtMl"
    "HNcz541kfDho+DENwNhAgnLNQSlNrO4gcyWb7rYwTx7qQrmaUtXBMoTvt0xDspqv8eJrUxQrNtGwxVBX"
    "tH6dB155f8GTqNb8zI8NEjQl2UKN75yYRSkvN/Gpx/vr+f0mQ9F4yTIF00tF1nJVWhNBppeKFMoOprwt"
    "YdL02TAk2aJNoWTT3xGhWHGwXeVXAF2liYYMtnd5rKFYcTDkoj+exltYWyJIImoxs1Ti4s0sluXxxHBA"
    "Ig2J6zZuA3hFgUjI9LO1UmxY0jqohgoVyw5z6RKtiSA35gvUbO/6WjhgYEhwHe3fVKnZrs/lLk5lGOyK"
    "Eo9YZAo1yjXXl2Y6U2U5UyEVC+Cq9URXo5DXEgvwqcf6UBpefH2KS1NZHhhOYhqCjx/poS0RxHYUiYjF"
    "OcczQs8d7/f9lmUKVnK1DUzdd3eifpnQdr1pbUdhO4pcyaYtESAVD1CuOgx2eBeoskUbrTQBU3LzVoFC"
    "2a4vVpAteNW9bV0x5tJlvn1ihqrtbko6epvpqWHAlLQlglRshXK99SQjJtGgQSpqeRLRHntJRS3iYZN4"
    "2MQ0NqfebmOH64bRkIKqo1jOVGlLeBcJBzqKPDjaAsBypsJITxzDEORLDjNLJXZvSyIFpHM1KlWHXQNx"
    "ju/rIBI0iIasuultAiQEtqNZzlaxXc3sUolkLICUnkpNLhRJxmpUbUVXSxhDCmq2y/hcHkN6lcRU1PIv"
    "qvh+atPWsc7BlNKMz+YYG0yysz/OaF8cKQRrhRpTiyUe2+vtkqs0N+bz7N6WxDQka/kas+kSo30Jntjf"
    "eUey3CDJy5kKL742jaM0mXyVQzvaMKSgUnP53ulFJIJS1eGJ/V2eYclV+e7bcwDUbMVTh7poTwY3G4p1"
    "OXm/Gg7ZMg2uzRa4MJlh71AKWT8HJ84vUSjbflLGMiUTdRUMBw1cV3HiwjJdLWHiEQvX9dTYvxFWz9kl"
    "ogG6WiMETImrNKN9MfaPJJleLNLbHqknUQXRmkk4ZGBIQXdbhIDVuMjl+bnb1U9cn8vrb7057YUBStPb"
    "FqIzGeL6fN6/YxS0JPuGU7TFg1yfz3N9Lo+UgtE+r2Z1fS6PqzTbu2NEQwbX5/OUKi79HRH2bk+xkqsw"
    "s1SiPRHkymyeZNTiF58ZRspGld7bnFDA4+yu0lQd5d8H1FDngZ50hL/7niCmFgrsGkisg7oxn9ffPjHj"
    "FboEPiswTelncBo3kBv1WtPw+trO+oVf738v9LBM6Y/VfCG2UayOBE2OjrXVOZyfFd+Q5NyYd9BNMdo6"
    "dxcCqlWFRnNk5zrLEMWKo5fWKhvo/KbSCetcrfnZVoJE34Sz/kzjHXK9ycOsB5VbbbpuLNqT60nPv7Zw"
    "/ofZ/i+aj+0qzMGJEQAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAABpAAAAgAgGAAAACMlHcAAA"
    "O65JREFUeJztvfePZNl15/m5z8SLFzYjIr0vb9qxmuxuUmqabhqJokiRIkajkTTa0QJrftiZxQL7Z+xi"
    "gAVmsVhhF4JmBA1kKUOK3qhFz2b77rJZlZVZ6TPDm2fv/nDfexGRrqqrq+iWB5VZiYj3rjv3nnvO95x7"
    "rpBSSn5JP9Ok/bQb8Eu6O/2SST8H9Esm/RzQL5n0c0AJk2T080v62SMj/kMAoYRQSkT0gSbET61hD5KS"
    "yTeoyArBz0vvhJRStjou7a7HRCUDUdNDKZEShBBoPy+9iUhGv2TEHhF9Jga/HyAhRPLAz2JXDQDHC/n+"
    "61tUihYL0wVG8hY524So7TJhWP9F8TOyygbNvD4jFFuURFArZrC1g3/LfW9Kor4OPv9T7qshgUI2RbXh"
    "8Jdfvca5hSJPXZzg5EyRYt4imzYwUjqGpg3PxH1M+2mTRIlrpCQMJX4YEgQQSEkQSmT0OfSlgyYEmqah"
    "aWBoAl3X0DSJiJZU0l8pf6qMMgRg6ILf/MAiW9UOX//BCrfuNJisZJgez3NytsD0WI5SPk0xZ2JZBoau"
    "ITTZF/E/YfmuJkm0BiQEocTxQ7puSLfn0+z6NDsu7V5Axwnp9DyCQBJGS0QAmoCUqWNbJpapk7M18pkU"
    "ubROOqVjpTTShmKcrolkxf40mCWkIoQQXL9d4z/9xSt0eh7vuTjBXtPFcTyQYKUM5iZznJ4bYWGqQKlg"
    "oWlaspqEePgiIh6oeCWHoaTe8dmu99ipO+w1Pdo9n67j43gBQaBWkR+EyJADe46mCTRNoGsahiFImRrp"
    "lE7GMsnbOuV8inIhRTlvkUlpCE1DRDtdPC1/EjwTMXYXhqryH725yZ994TLvPj/GY2fHeeNmlVbHJfA8"
    "1rfbVJsuoyM2j54e5fGzo5yYLWAZOqqMUIkcAbqIO/FgeiEHFBkhoNZ2Wd7qsLrVY7fRo9Pz6XkBQRAS"
    "hvs6eVQT5D4lQoAuJJqmYeg6dkojY6cYLVrMVGxmxmyKGSPZp6NXHvrqSpgkpWKS54f84z/f5IUfr/Lv"
    "PnmR8bECV1dq7DW6eI5Po9Hl9kaD7VoPO2Vycq7IhZMVLiyUmBzLog+ogqGUyd71TjoyKGp6js/tnR7X"
    "11qs73Zodjx8P0BKgRCJ/L3/AYlWipSqDE0ITFOjkEkxUbI5MZlheixN3jbVs1GVD5NRYhAFD8MQTWg0"
    "uy7/8b/8GNPQ+L2PXyBEcGe3Q8rQSZuwsdPi2q0qt9aatLouIzmLhakC81MFxko2Y+UMpZyFbRukDGUv"
    "J/ZXNBR369N+cN7xJdWGw+pOhyurLdZ3u4RBgK4LBOKAlvagSERtD0OJpumMl2xOTmeYG8tSKaTIWDp6"
    "rME/JEYNMWlQ1b5yq8of/81rnJgp8vsfP4+Z0nlzucZOwyVjGYxkU2iEbOy0WF5vsLLepNPzyGVSTI5m"
    "mahkmBrNMTWaoRip9IauRbOUZFiP6ljMVCmh0fVZ2+1xbbXOrc0urutFtptIxJVq9+BucTiCclD9PoqG"
    "GS6EkgpBKDAMnclKmpOTOebGM4wVTFKG9tAYJQ74kySESIIg5KXL2/zXL13h3RfH+e3nzyAE1Fsey9tt"
    "bq63CYKQiVKa6bKNIKTRcriz2eLaSp2tvTYyFIyW0izOFDi/WGF6PEs+k8K2dIQQB1bL0GdCIEPJbtPl"
    "9eUGS2stGm2XIAgAsU8tHhjQQeXiALsG7KeojqTbb0vNFmhCYqUMJkczPDJfYGE8Q9rSkqoeJLMOMiki"
    "KSWOG/CFb9/iCy/c5Pd/4xwffPccQRDS9UK2qj3eul1jdbtHztY5MZllYSJHyhC0Oi471Q6Xb1V548Yu"
    "GzsdMukUJ2cLXLowziMnypQKaQxDQ9PEwL4V1R3Vv1N3+dG1KjfXWziOn+ybIl5FAwMb7yUgEJpASKU+"
    "G5pA6OrZwA/xQyUtwjBEiMgmQiK5dzVbRuJGINF1nVLe4rETI1ycz5FK6Ynx/KAYdSSTwlAiBOw1evxf"
    "f/kadzab/C9/cInTcyVClOG413B4a7nGW7cbeF7IZDnNyakci9N5MimNVsdjt9ZlabXOq9d3uLlao+eG"
    "jFeyXDhR4tL5MU7MFLHTJqau1HlVr2Cz2uP7l3dZ3mjj+2G0KPZjCuozKQW6LrAtg3zGoJSzyGdMspZO"
    "yhRoQiOUEs8PaDsBzY7PXtOl0fHo9QKCMEQTaoWFB1bpcaSYKyQUcikunS5xcbGAndIT5j8IRh2zkogq"
    "gTeWqvzJ371JpWDybz95kZnxPEEo0YSg1fO4vdnm6mqTO9ttBIKpis3MeIaZSobxUhohJeu7bZbXG1y/"
    "XWd1s0mr66HpgnwmxdRolpOzI8xN5JgsZ/Al/OBKndeW9ug6HoYATe/bZDKykXRdo5A1KectKgWLcsGi"
    "mNHJ2CZpU2DqaqWKiKOBlHi+xPFC2j2Pettnt+6w03DYabi0Ox5ShgmctB8KO4xJCjtTq7OYt7iwWOSR"
    "hQKlrKkG+GEyqc8sZal/99UN/vLLVzk7X+R3f/085WI6GaggCNms9bi50ebWWpONWg/bVJvrRMlmqpJh"
    "ZjSDZWq0ux6rm02W1xvcXGuwW+vS6/kgwE6bTI/mKJcy9AIdoYEfSGptj1bHww9CQGLoGiN5i8lSmoly"
    "mvFimmLOIJdWaMjgEB7o8MDffiBp9Tz2mh6bNYetvS5ru10abQ8hZKKc3BtJwhDy2RQXF4s8cWKEkZzx"
    "QFT0e2KSlOAHIZ/75hJ/89Wr/Pbzp/nMh08rbS2WQFIBtRt7XV6/VePmeotOL8BO64wV05yYyjI/nqVc"
    "sLBTOlJCq+NSbfRYWq3x1s0qN9fq7NUdTFNnopJhdqJIuWRjpEx6nqTVcem6IaP5FKdmcsyPZyhkTSzj"
    "EN/lcYOyX1eS4AYhtZbHjbU2N9Zb7NR6BH6Apom7aIEDVSIJQsjaJk+eLfPEyRHslBY15yEySXVCPbJX"
    "d/i//+Z1rt3a5X/6N+/i0vnxIfkd+6OabY83V+pcvtWgEa0A09CYLNucnyswP54hmzbRdIEuJH4AXhCy"
    "V+/y+rVdfnx5kyu31P41NWpz/lSF+YkCumWi6zrn5nJMlmxMXRua6G93sx7sehh5Pb0gZKPq8OpSneXN"
    "Fq7bV1i4h/LVviYp2Cl+5dExLsznEwP/fhl1T0yC/oZ+Y6XOf/qLV8jZOn/0W48wP1lA14crl1LiepLl"
    "rRYvL9XY3uvi+iF+AHZKZ3rM5sxMjqlKhmzawNRF4mDsuSFdx2X5TpNXr29zeWmX9b0u6ZTB3GSec4sl"
    "zsyNUCna5LJKnTd0DUMXiTJxP4MxiAtKCfW2z1srDa6sNGm0HPxI9b/H0pASpipZPvTEOFOjabT7bBe8"
    "DSbFj4USXnjpDn/2+Tc5MVPkv/nkRabHcodusp4fsttwWd5qc2OtwcZuDz+QmIZGJm0wPmIxPZZhpmwz"
    "VkxjGhpCUzaI50taHYedWo9bdxqsbLbY2GlRbTiEUjKSTzM3VeDUbIHZiTyjIzZpS0cTypyV0f/7gd97"
    "6WNMbSdgbafH1dUmtzZa9Fw/fpK7l6oUq3MLI7zvQoVS7v4ViXtmEvQ70en5/NO3b/HXX7vGh949wx98"
    "4gKZtHlo0yXQ6fps1h2WN1pcvt2g1nQxDIFpaNgpnUIuxexohsWJDNOVDLquESLRI9i65/i0Oh7btS7r"
    "2y02Ik1xfatNx/Ep5i3OLJR47PQYZ+aKjJVtBEJ5l2P0e4BZ92QHRc95fshe0+PGepvXlqqq7bqMTOLj"
    "mKVWk5UyePJMhafPlTCN+xN7b4tJgx2oNhz+9B/f4ruvrPHvPnmeX3v2pCpwoBF99AD8AJodl5vrbd64"
    "WePObkc53zQFYqZTBpW8ycJklpPTecZH0mhCJI46TQhCwPMC2j2X9e02t9eaXF+tcX2lxk6ti2kYzE/l"
    "efzMKBdPjbI4lSOTNpNBCyJ0XBNvDzuUCFpdn8srDV68UqXedjD1/ajGQRJIAgmlvM1H3z3BwritPn/Y"
    "TIIIiNU0rq/W+d/+5EWCwOc//N4lLp6sJK6EpCGy75LWNPB8WFpv8uqNGht7HRxPyfowct5l0jqLE1lO"
    "TeeZLKcpZFIYhkgCZZAysn0UUlFt9rhya4+Xr2zz+vU9tqod0imd+akC5xfLnJorMlnJMjqSJm0Z6NH+"
    "d7DbhzOuj3IIur2Al5ZqvLZUo9VxkveOJ4kfwpNnyrz/0VHSKeXWeTuMui8myWjgw1DyzR/d4f/93Guc"
    "ni3yR59+lIWpfMSoYVys/x7ommCv4fDaUo1bW23qLQ/H8xFCQ0qJH0jyGYPFySzz4zlGixb5jIFt6hiG"
    "YujgChNCEAQhazttLi/t8Nq1XZbu1Om6IcW8ycxYnhMzBSbKGcbKNpWiTTZtkh7AEGNXx2GDl2h3Elw/"
    "4NWbTV69sUet5UIi+I4We2EoKeYsPvzkJCcns2/bdXNfTIobDtDqenzx27f4+28u8eT5Mf71r59lajTX"
    "r2BfYwYZ1nMDNqo9rt9pcGujTaPtEQ7geEJoZCzB+IjN9GiamdEslYJF2tTRtX2xgpH67/khna7H1l6X"
    "O9tNbq7Wub3RotbqgRBUCmnmpwosThVYmC4wOpLGtkxSpjbcPg6GtCV7shPw1kqTl65VqTZ7iavibvvT"
    "ufkRnntinLytvy0t9L6ZNNjoasPhz794mS9/d5lPffAkv/tr58nYOkqEHN6Q+F3fl7Qcn9XtNq8v1Vjd"
    "6SoHhBCEUoGYhqYcb+W8xeKE2rMqhZRS/fugefS/SIxv11MKR7XhsL7T4upylau3qmzsdhBCY2E6z4WT"
    "FR45WeHEdJ60bUaqfB8fHCw3brcEur2A1283+dHlHTo9LwF9jxgpQgnplMlH3zPJ+TmlDd9rXOM7YhJE"
    "fh8huLFS43//0x+zsdPkf/3D9/C+J6YUuq3dnVEhSl2vNhxevrHH6zcb+EGIZepR/J96XxNgGhqVYopz"
    "cwXOzBQoZAxiRLzfq2EnRRCE+H5IIwJ8b6xU+fFbm7x5c49aw6NctHns9ChPXhznibMVJspZRITOB5GM"
    "1rR9LJDQcgK+9+YuL1/fA0KEOC5qW+IFksdOlvnok+NYphaJ2LuP8TtmUjyzgkDyLy+t8cd//Srj5TT/"
    "w796gvMLFRAxrH/8+0KADKHacrmx3uLycp3tmhMh1FqEYyoNTROQzxhMlW0WJrPMjsbwkE4fG4iHhkTZ"
    "iPGrdtdnc7fNzTt1Lt/c49pKnZ1qB13TmBzLcmJmhNPzI5yeK1IupslYaoUN7k2xP2Jz1+GfX9vi9lY7"
    "ckEePep+EFLKW3zivTPMjtr3AOAqesdMUmMgI3sm4HPfXOKvv3qFJ86M8nsfv8CJ2eI92SdSkmiArh9y"
    "c73J0nqbjWqX3bpLEEp0TZURhqrDQsBowWJ61Ga8lGZ8JE0lnyKTNo6oI9o5BmIIa40et9YaXF2ucn21"
    "xk6th+sFWCmd0RGbiUqW2YkcM2N5xis2I/kUpq6wx1CqwJvrd1p8761ddmq9xDt8RC+RCH71sXGeOVdK"
    "xN1doaYHddJPubsFtZbDn/zDm3z52zf5tffN84effCRCzIlm813KCWUC2DY6Hre32lxZaXBnp4vjBkkY"
    "WWxKxn6vrG0wPpJmdlRF9VQKaeyUQbxpI/p7QGzkCtH/3A9Cao0eW9UOS6t1ri5XubPZotZy0HSNStHm"
    "xEyRc4sjzE8UGC1llKgVAscPeeVGje+9sY3j+WhCOxSU1QS4XsjiVJ7feGaKgm3ckwLxwJgUdx5gabXO"
    "//kXr3B9eY//9tOP8vFnT5Ay9Mjyvzujkr0qlPihZKfucPl2naurLVodN+qYRl/x7W9CKUNjomxxairP"
    "3HiGkVwqqlse6toe1DbDMEQi8PyATtdX3uXlXV67tsfSnRrNlkfGNlmYLvDYmTEuLJYYr2Qo5ix6bsg3"
    "X9ni2mqd2E+sxY6sqHFaZDOlUwYff+80Z6b7WvBx9ECZNCizv/faBv/Hn/8YXYP/+d9c4skLE+jR7vt2"
    "GBU7+HpeyLU7TV65vsde0yWUcVzCsOchtntMQ2N21ObCQoHpSlYBsVEw5H6N7bA6iUSZ44e02h631uu8"
    "9NYWr17dYn2niyY0JscyXDhZ4Ymzo8xP5Five7x8o0anF6hChEzEeJ9Vyg58+uIYH3xsNLHzjqMHyqTB"
    "jjpeyOe+cYM//Yc3OD1X5N//7iVOzRZBE/eseg6WF5e5Ve1xeaXO0nqLVsfvP0csAvuqstAgZxlMVNKc"
    "mMwxU1EKRhxmdhizFH/kkIYIyoXR6XhsV5V2+ObSLktrDap1B0PXGB/NsjBdpFRMY6RS+KGg6wR0HR/X"
    "DwlCtYdqCNwgZHYsy6d+ZZpiJnXXMXjgTIK+IrFb6/GfP3+ZL7ywxLOXpvjvfvsxpsfyyDBEaPd2yFAy"
    "KKYUdFRreazvdrmx3uTWepuuE2DoygKONSa1qtXeYxoaOduglLeYrKQ5MZFlomRjGtoRAZySw0YlhqI6"
    "jket4bC112Flq8nqRpPbG022q11cLyCTTjE2mmNqLM9oOYNp6nRcSa3l0un6+EFA2jL4rV+Z4eRU9q6q"
    "+ENjktJ+4OZanT/+m9d5+fImn/7QSf7gNy+St00k4p4Uif3lqlYLXDdgp+FwY63J1ZUmOw1HnZRImN9n"
    "biwaDV0ja+uUCxazoxlOTOaYKKWV93VAfKoq9ovC/veJYRtC1/GotxxWt1rcWquzfKfBrbUGO40eQmhU"
    "RmxmxvNMjOcZyacJEVQbLvWOx/sfH+Ppc+VD6xukh8YkIQQbez3cIGRto8F//M8v0mj1+Pe/d4mPvncR"
    "XRvw9bxN8Rc3WEhB2/FYWm/x5nKDtd0Onq/A31j+748xiGPebUtnbtTm5FSO6bEMpVxK7ZkMn8U6CsuD"
    "fgCnEBoSdTBgr97j2nKV12/scOVmlbXtFq4nVTjAZI6F6TLTkwWu3mkxP57h15+ajEyLoyXLwxN3wHfe"
    "3GN9t8fT50b45g9v8+dfeIupsQz/4fee5JFTo0pEHTEQ91LHYMvXdru8slRjbadDq+tHQSscqlgIFJIQ"
    "BpJs2uDEdJZTUzlKhTR521DYoB69d4whnrQDtVr7a1gpBzdX63ztB8t88ds32a07VEYyvPfxGX7l0ixX"
    "1tpkLZ1PPztDPm0cO1EPt/reAalZKKi1XG5vtljd7lDIGjx7aYbtapcvf+cm//WLl/mjTz3CmYVyEm71"
    "dkO4RfKioqlymlxmjOWNFtfXmmzu9eg4gVrVcduiBoZEB8gMQdcNuLzcYHW7y1QlzdxYhomyzUjGJJ0a"
    "YFas7O9rZ8x0MbSPCVzPp911qTUdpIQTM0WeODfJ4nyF6xsdGi2HMDRpdrxI/B89BA+cSTHd3uqwVVew"
    "ztpul0unR/idj51lu9rhe6/cIWMZ/I+/8y7GSvaA2Hh7nBr0WWkaFDMG5+cLTJTS3Nxo8dbtOrv12K6K"
    "lpQgAVATFR5otD06PZ+1nQ6lgsXCeJZT0zlKOQtNF4h9Auc4PLLT8/nuq2t8/p+XuHa7ysxEgQ8/s0A6"
    "a7Nedeh0PQTQdQLqbY/pSqyjH17mg2VStBf13ICljTaO6yMRTJbSFGyD0XyK337+NNdv1/j6D1c4MVvk"
    "Dz5xsT/T5X1GfApAqpWVMjTlf7JNJko2L13b5eqdJkIKDCPecyJ4SAytMfxA0u6FdN0u29UeN+40OTOb"
    "5/x8kWJWqcqxHytxTkR2WSgluiZwXMmXvnOTv/rKVe5sd3jmsSk+/fxp6j1Y2mjjur6alBr4fshe071r"
    "9x4ok0KUXN6uO2xVe4SBpFRIc2G+gJVSDqDHz4zy2x85zf/zt6/zuW9cZ34yz/ufnENKmXhM7ytYI3IV"
    "yGiwMmmDubEMdkqnUrC4vNKIgh5FX1QmGkKsAisGBoHA9wO6bpd6x2d9t6fiBiey5NImui76QGsi5gR3"
    "Ntt85Xu3+Kd/ucVu0+FDT83xsV9ZxMXg9laDjuMlxqsQEMiQWtMjCBk617WfHiiTFPgZcmenS6vjYRga"
    "Z2fzTJWtxPJOWwYfe+8Cd7ba/MM3r/PnX7xMMW/x2Nnxe0aF79YGiMKQNRXynLMN8lmTW+tttuo9mh0f"
    "kOhCRK79YZe/YrTyEtfbHs2ux3a9x/puj6mKzdiIxUjOJG2aCKDjuFy9XeObP1jhWy+ukEoZfOpDp/nQ"
    "kzN0Q41XruzR7rgHQt8EUG97uF6IbR3tuniwTAK6URSr6weMl2zOzeYGzu6owRsdsfnsh0+zW+vwrR+t"
    "8uf/dJlCNs3J2WJ02uEdcgoi20e5rnO2weMnSkyVbBUKvdFis9rD80N1CO2Q6mIcMhWJyL2GS63lsbLd"
    "ZryUZqpsM1nJYAjJK1e2+PoPlnlrqcridJHnnp7j2XfNkM+m+KcfbNDqepi6SLzOyXgJaHY9Oo6PbVlH"
    "9uWBMSleBY2Oz27DASmZHctQKVj7oj+V/F6YyvOZ58+wstnmu6+uM1ay+aNPP06laCWBmA9iVcXog64L"
    "Jko2hWyKiZE0l1fq3Fxv03Y8NKEN1DcsbmN9QdNEhPJ7NDo+q9sdJspdOs02X/mXJXbqDu++MM4n3n+C"
    "i6cq5GyTQEI+a6ALIgYNd0gX0HV9Oj2fSsE6Ur17gAmgVG+26w6Nlkc6nWJhIkvaHI6O6ausgndfmODT"
    "z53CShl84YUlvvSdW7hemJT1oCiuU9OUEbswmeP9j4/zxOkRcuk4aLHfh0HTcUgMJt8rzWx5o8ULL6+z"
    "vtvhqUcn+f1PXODJCxPkMik0TWDqglIuFblXDiIYQghcN6TjBINDeIAeGJMUrhayvtul4wbMjmWYrtjK"
    "RXDgWTVrNQ0+8ewiH33fCRxf8pdfvsKPL2+hFIDwkLCrd9K+yF0gQNcgb5s8c36UX3t6ioWJTN/Okf19"
    "6WCbh7+TEno9n/c9Mc1//9nHODNfwjQ0NNFnQjGbImVqyPCQeCIhCEJJ1w04bmI+EHGnDDHBXtPlzk4X"
    "O21wdjZHNq0fClSq9qk9I5M2+cxzp9jabfPdV+7wZ//4Jpap8a5z48lAPIAtKqlzkKyUivHLWga3NtVe"
    "tb7bIwxJopGOajeAjI7inJ0fYXY8t0+1V38XMga2pdONjvcMFiqAIIR27/g48wezJ0UjuVl1qDYdJss2"
    "s5UMGrGNdngD4gjVkzNFfudjZ6m1erx0dZu/+PIVClmLU3MjQ6lmHhTFRYUR6Do9miGXMRkbsVhaa3Fj"
    "rUmj7aPrg++Iob+FADdUfqORfDoZhj5orP7P2gbZtMFurcd+RsQithuLu4e5J4lo2W7WevhByOxYhnzG"
    "IOTugxt//e4L4/zWc2fIZSy+8/IdPv/CEp2el2hpD4PiloVSkrcNTk7meM/ZMu85V2GqYifujqNeDvwQ"
    "pExiKvZrbgApU5BNxwk6Dm+DF4QxGHIoPbA9qesG7NZ6WKbOVDmtzsDew3v9/UnwgUszfPDJWTRN52vf"
    "X+ZbL67iuP4RYcHvnOJ9RvQ/YCRvcel0mfc9OspMxT5yqxCRm10TgqytlI/DHjU0dZb3UDRdFYTry0Tl"
    "P4zeMZPispsdn72WS6VgMVa0DlUYjmxE5M8p5kw+8/xpnjg7Tq3p8F+/eJkX39zE8xWifVxH3gnFzNIi"
    "14muCU5P5VkYt/G94MDzSsFQsI7QBNnM0dFJuibIWAaHYenxJ54XEMiDykpMD2wlVZsuPSdgbjxLPmNG"
    "1vO97yOapkK1zi6O8IefvMip+TI3Vmr8l8+/ydXlvcRD+7BEH/RXtRAKx1u6XaPZ6kVtO6jtuZ6PoYFt"
    "mUeUCCBIm+JQ2EeiglNC5ZU8UkF6AExS02q36WCldBYm4/xCb38wY9Fz8VSZz3zoNIVcmss3d/nLr1xl"
    "a7cbnV+VD5VRMY5Xa/W4sVJTWcqQ+7zIEoTEdX1MQyMV24L7VouMRj1t6QrvO1xdxAvDA5NgkN4xk4RQ"
    "IcJ7DY/RgsVYIcX9GqOx2yCd0vnVS9M8/8w8QSj43qvr/N03rtPuuIeKjQdLyqBY3+6wXe3iRynZhg1c"
    "1QbHDTANHcvUDy0plvgp46Ax268tXqUPiUmRckzHCWj1fKZHbWxLTwy5+yGlJEC5kOZTHzzJU49O0er5"
    "fOk7N/nnF+/gRvvTw1xNUkpurNboOD5BEOD7wZAoisPMXM8nZYpkJR2pQg9ATvtJxLEYERp/6PvvpDMx"
    "VZseYQiT5fQDS6obSsnp2RE++5EznFsss7nX5W+/cY0fvbGhMqTw4BkVT65G2+XKrSpSqhh3x/EZHMDY"
    "f+i4PumUiRUdmzmq68fG8SeVH/3VO2NSVPBW3cFKaVTyCsl9p4bnILj6rnNj/Mb7TzBeyXLl1h5//dWr"
    "XL61RzQHHyij4rJurjZY2WhiRolEVJqAPkwVQ2CeG5DNmJjmwYMCQ/05RkgfffisT++ISbHrYa/pUcgY"
    "5KLDUQ+CYkZZKZ0PP73A80/NYxg6L761yd9+/Rq7tY6KHJYPTpGI+/Pm0i6tjocWxTd4rn9gKGUY4vkh"
    "GUtHi6GVI+i45gkp1TGbY3j1jsVd2/FpdX3GipZKGfMAJVAcjFjIKPvp0oUJwhC+++o6X/neMo7XF0Pv"
    "lFGxR7jadLi6UlUDF4FtjquUh9jtEdtIfhBip1NRrN8RxirRAYFj6jZ1TUX1Pmg7KS6u2fWRwGQpHX3y"
    "YLWvWOxNj2X55AdOcWquRLPt8vkXbvDNH63iuAeNzfusCYBbdxps7nQxB8LNPM/D9fsgqPosIAxCchkz"
    "ifE7vESilNeDnww/pcdxgkdhnPfdp4ganYC8bVDKHcSvHgQl0I2AJy+M8ckPnmJqPM/yWpPPfeMaL13e"
    "jE5D3P9qijBtQhly7XaVruMPAaWBH+I6ftI3CXi+ChfLZ48zZBW5vkrgexiFKFe9OEbjum8mCeLwpYCx"
    "Yio5+v4wKB6crG3y3Htm+fBTC6TTKd5a2uPvvnWD5fVmorrfF6Mid0in63N9pRbXmtQtpaTXVSc54hc8"
    "L4hOHN494N5xw6NdLpIkBcJR9I5WUhAqSCP2Pj5syAYJpYLFx943z+Nnx5DAS29u8vkXltitdt+BVqkM"
    "2LXtDus7bRVZO9AXKaHneFFqUQCB6wXoukb2OCYJZaS6fngo7hi31jSOP2D3jpjk+iGaIchnYlH3cNEA"
    "EQGxC9N5fvMDJ5mbKtJzA/7phSW+/qPbtHsqhu3tTpY4VPjNpV2aHeUeGZz2Qgg818f3VJQRSFwvIGXo"
    "ZNNHizuBim3ouUd5mVUOJMvQ9vsDh+gdMckPJGlDJ2vpx1Tx4Eigxk4TGs88OsFnnz/LeCVHo+3zt1+7"
    "wQ9eW49iJO6dlKNOo9lyee3qzuFotQA/CHB6HnEkrOsGpE2NjHWcmFd+tk7P5zBoTkZBL7ZlxB8cSu+I"
    "SaGUWKamEhs9fB4B/dVqWwYfePc0H35mnoydYm27yV999SqvX99Gcrx/ZpCkVEx99do2125XMQ0tUUIG"
    "3eEyJEIeFHl+oNKIxgO8n7lR9Z4n6TohgkNQ7sjRl04dz4b7YlLcfd8LSUWXbjx03HOAYiB2tJjmI+9d"
    "4LGzY4Sh5K0bCpFY3WwpURPe3dCNk3P86I0NVjcbOK6PkMNAXRwz7np+dDGJUsGztol1hMIUF9HzArqu"
    "f6jWEEowNJWp7Di6LybF1flBiGXEhfwEuURf3p+YzvOZ506xOFvCCyQ/fGOTL337Fq2uB0fbh0Afq9ut"
    "d3n9+g6dns9urUO74ybvxa8ntlEYACGeH5DLDjDpQPfVm103GMiTN9B+AaAyaqZTxhFlKLp/Y1ZK0IRS"
    "vR+ywnAYxbaTrgmeekQFJU5UsnR7Pl/9/jJf+95tWm13KLpnP8WfX1uusrLR5OxiCaELNndbtNpOdMap"
    "b6oGQYjnKfso8EMKWUudbOdIHtHuBjhulCF5XzNCCZapqaTvx9B9MykMJZapH7ncfxIUi6qUqfP803N8"
    "4N1z5HMWa1st/uZr1/jB6xuR0XmExheN7ItvbRJKyaeeO8Wz75rFMDS29to02w5e5D4XqMAT1w0IAoXd"
    "FbMpDOMo00Ppa82uF50+3JdwV0qCQMXG22akeD1oxSF2zhn36YV9UBR3frSY5reeO8kT58bRdZ2ba3X+"
    "+qtXubFaS1wLgxSf4qi3HX742gYnZkt87H0n+P3fOM9zTy9gGAa71Q7VRgffDyAKP3MdX90yA8eiDQqs"
    "hUbXI5DDGmefqZKRnBllPD46rPq+maRpAiu+xuAnvB8daEu0oubGc3zm+TPMThbRhODyrT3+/hvX2av3"
    "ENqwxhaP0+WlPZbXGzzz6CT5jMlEJcO//eQFPv7sSXRDp9l22Kl2CKLkiY7jRReaCLKZOMj+cCjBD0La"
    "HZ8+j2IlRBBISUoXzI9nMM3jgYD7Z5L42bo1Mw4Le/xMhV//1UWKeZswkHzzhyv8wz/foNnyDsR4h6Hk"
    "2y/dwTB0nrwwjkCFYE1VMnz2I6f4xAdPksum6fQ8dmodeo6L7/t0Oi6aJshljsftel5Iq+sn9fWrlxBK"
    "JkezLE5m7yqI3lkEq3j4EQf3SkKoxLi2ZfDhp2fZqXX4ynduUWt2+fwLS5QLaT76vkUsU1eiThOsbTf5"
    "wRsbnF4YUYlAIuNSSpifyPHZ509TKdh85bvLLK/X8YMAoQl6boihC/KZfrzdUJhKhNO1ez7NrsouGTNI"
    "KXWSjGXyyOIIpWzq2Chf+AW7VjsGfScqNp/84Ene8+gUVspgc7fN3379Oj96YwPo7wlvXN9lZbPFU49M"
    "Usilho7chBLmJgr8xrOLfPYjZzi7UKbR9tmrddnaUV7bo8FVxbZ626PbCxLGKw0vxNA1LpwY4dRMlnvJ"
    "OfKLxaT45IMUnJwu8JvPLjIzUQAES6s1/uorV7m+Wk1O8b18ZYuUqfOei5Oojbt/4k8xSlIupPnw03P8"
    "q4+e4+xiWWWirHexTA07Di8+0A7FpmrTxfWjQ3GCyAWPyrh8skTuiJRv++kXikkxxZLjiXNjfOTpefIZ"
    "C13T+P5ra/z9N67T7LjUWw6vX9/h/GKZM/NFYFgDTCJahXKRfOSZWX73188xP11E1zUsS+9HCQ2QUvcV"
    "+LzbcJNwLYEa7NERm0tnyowWzaG6jqOHliLgp0mx+msYGp/4wAl2Gj2+8t2bBKHB175/m7MLFXIZg43d"
    "Dn/0/lNk0mZ0Z5/YV87wxVfPvmsa09T4iy9doVRIJ8l1D9YvaLZd9hpuEnmrCUGllOWp8xVmK+kEt7sX"
    "z8EvJJNAJYUPpaRStPnMc6fYrXX53strNDsen/v6NdKWQamY5j0X1Tmoo8Zq8EinbRk8/cgE6ZTObq3X"
    "j1w95N3tukO97SanGqdGM1w6U2ZhIosZnV6/V9fOLyiTFCkzW7IwXeCTHzjJ6kaLpdUqq5tNHC/gQ8/M"
    "MzuRT2yXY8uKNv9s2uBdZ8dodbxDY8AFKpHiZs2h5/mKQZUs7z5bZn48Q9p8+xc0/kLuSTElZ2UlXDo3"
    "xmc+fJqRvB15SuGxU2PYlnEAjTi6PLXfWKZOpZhWpwH3vyxUvvOdeo/Al8yNZ3nqQoXFyaxS/++jH7/Q"
    "TIJoBaAwsuefmuUj751HCEG5aHPxZJzG7O2W2X/n4IoQVJsera7P4mSO95wrsziZiaKP5BHvHE8GPNy4"
    "6p8FUhGn6iqC33ruFNeWq4wU0sxP5QdgovuMNJKwHzJQcYg2F+fzLExkDvoDj6nrMAYmF9T//4HiAf2X"
    "l9cRwK9emuHeL4O7OwnAD2Fjr4dpCip562DS97uVcRST4KeJY/8EKYJrmh0XpCB3DzFzb7uKyEbSBSqi"
    "9144dFS4V0RCSil7XqAs4/0g1C8YRZF0kbgR8b8HXokMVfn3uvVIKbFMg5TBodwyAG5udLi22oxS/e83"
    "6A4r9JC2ibt/d1wZ+595u98fVxcoVdxKGZiGnvjXHpZDOcHp7rF81wt4ZD7HdOXwqxEMgJ1aj7eW66TM"
    "2PSKa1Pp0fZTHFo12Kh+LMBQCUjk4YxjmLGHjbl2l+/313VshJCAc3MjjOQGQNGHJePjJt2lfCkUErHa"
    "cGh2PKjYhz6XaHdBEOBHl0zFdSigUPT/lgN+kSGgS/0SguGjixH+FZ8uH2qgpL9pDwUixkyRyXFGOeC7"
    "GnBqRqcV+rfraZq6Qjt2DQxOAqEJpispzs/liG9a+GmTlGAaAs91CY5haB9xECLJRJVo9FIOvNyXsUpj"
    "iSW8GiwV/CdImULF4ukajq8iPcMw3uxk8o6m9+sK5HD+UiFUknMtvshqaKX2755IGTppU0PXBY4XqrqG"
    "OjvQF8DQBemURhgy9PlhdK/i9cB78a+jQxYGypTR9avHm6sJ1i6lJJPSmarYqoFCHYG/s9PF9SQCxQhd"
    "wFTFVgkmovDczWqXZjugmDWZH88yO54hm9Zptj2Wt9qsbnVo9fwEIU6ZGrMTNkaUwqzactnc6ybQC1Iy"
    "UUkzkk0RIml2fDZ2u0mndSEYyadYnMwyXc5gpTT2mipH+EbVOfw4jFSMj9nW80KCUB7KLF1TN3cOXgTt"
    "B1JFx4qDzw9Kt7SloSPoef0T5Yc9r1Y35O7CoD6TABmCldJ46lyZTMSAnhfw9R9vcHuri25qyECSsQ2e"
    "Ol9hrKiQ3FbP5xsvb2AZ6vPZMVtlAdYEQQlmxzPcWm/z42t7VFsOQSBJWybvPT9KxjLRNbi12earL/aS"
    "2yslcH6+yPnZPIGEG+stNve6yYY8PWbz5JkyU2Uby1R3pE9W0kxXMry1UueNm3V6TqAQ6EO0Az+QXF5p"
    "0uy46tDxwCBL1IUfkyWLyYqFGd0ys1ntsrTR4bBDefFq13U4N1cgZxtcWW3SbHvRvrmPSQK8QFIqpHji"
    "xMi9M0kIlcMtkFDKpZJ9ZW4sy+p2NwnimCzbzI1lkoC+akv5TC6dLnF6JodlqPAkKQSGBlYqhb1g4HgB"
    "339rB9dTaWiK2RS5KN3L4qSgmEuxU+uh6zoyhKytk4+S0+bS6oLEIAgZLVo8ebbM4kSOlNHXRk1dYJV1"
    "rJRGu6OuG4VhsRaftwtDqRi/24lOUDAkojRNUCpYPHN+lPkxCxBs1x1eu1lFPyJkIJAqFcBU2SZlalxf"
    "21f+Pia5vmRhKsdjC8VDyzuUSZqmfPIr223mxzNJdt7Jio1lari+xNAF82MZ0ik90aTWd7tMlGzOzuVJ"
    "RZf4qhHp7zNpU+fCQpHlrTZXVxoDgYKSMIScrZLabuz2ksxYfQVBEsfs6hqcm89zYiKLHqXLjEc2/rOU"
    "T3F2Ps/t7Tbtrp8kvCCpUxXX6wW0uj6GLpKjlkQiSBm8PgXbZLI0imUaeH5Iq+OrmwGAvlZDtK+Cb+rJ"
    "qb5uz0/K71c8wCQvTLI93420pCKhOr26FV0mFfmAy/kUxZyJHwYUMyZTkZqoRSuv4/icmslhW/0E5IlS"
    "ocX3w0qK2RQX5gvJjSvJDhupoYuTeaxUFNo02O5IXoRSYW+np/OJrSPoPxqDngKYqWQZH0kfiZGpLVci"
    "hIq9y9gGWdskY5vqam8gDAJub7apxzfLiH4d6gJjDU1o6Hr/ZzC8TT0rk1Mg+5/V9Til6N01kiF/kq4J"
    "Nva6rFe7LEZ+lkJG5dde3+0xXkpTyqeSGOpqdD32RMmGKKjdDyT1tkvPDcimVRbhOJPiiakcY8U00f47"
    "RLNjNhMjae7sdA/Jw6Nm53TZppK3osBGBb9UWy5+oO74y9vK7ZC1DebGsixvtI7suEB5b01LcGa2gGWq"
    "dGetjsvtzTadnkur61FteIwX032RKSUjeYuRvHVAzdf14aMwsVtjbMROrtSOGej5kvGSfU+mQF9xkKBr"
    "Gl3H5/qdFgsTuSSEd348y5WVBhPlNOlUdEeqlGzXe9gpg6wVX3sG2/Uer9yoUm95jI2kedeZEuVcCilD"
    "cmmT6dEMy1vtpAFaFIqVsQxOzuS5M6DFDbVNF0xW0qRMPbkUZG2nw2u36rSdgMWJDI+fKGFbOgKV+MO2"
    "DNo9dcnw4LSQ0UiFoboM612nRhjJmoRSaX3fCiVXlh18QrrRcZd4jUgpWZzM8cTpUv9qu6hQAeQzJl1H"
    "RQiFoSSfSfH0hXIygWIoKpRqH41dKffEpD4JVra6NNtedIJP5daeqtiMFS3iQ1RdN2B9t8tCtD9IqVTU"
    "N27VuXy7Dgg2qj1ytsF7zpaTKJxK0WJ1p7OvRkXz41kylp4MzCCTVOZ8dcI93jNevlHl5nqLEEGr4zFV"
    "sZkfywJQzKWw0wbtXpxy5gjRJwRpQyOd0ghCsFM6k2WbK7frSCA8ZKqnUzrlnKlU+H1bnq4Juk5ftdd1"
    "QSFrUs6a+FIm2TSTF+6BhpR0iQrGqLcdtmrq/p9Y5D16YoRKIR4kwW7Dodp0k+sBhBDsNh1urbdwPHWW"
    "tusE3Fhr0nH8BIIvZMzkoNbgQAFU8iblgkUYDoOToVTZGYtZdZGiELBVc1jZ7uJF53ZrLY+dmpv0PW1q"
    "atXL447nq6dD+te6gSBl9E9sxKcm4nKViOsb5f3NsJ/g8LCxl9EkTZ4TwzeyHSf2DlhSmiZwvZCNvV7S"
    "cF3XODmVI2ebSadvb3XwAkne7h/F3Ko6NCMNKC5ru+ZQa3rJoGfSulIeEiVQqfahlKQtnemyzX5zXUrI"
    "pc3khHsYwlatSy9WcFBw1OZel9WdDuu7XbbrDjJMkkQfMwT9QRORgrLXdPD8EDttMLLPnZGoBoPu2fg7"
    "eXCoBxWpQ7+8W/M4IO7UPAiluo+o6/hkLJU3J2PpxGn62z2VvNzU4wxVStxVWw5+2L9JRQh1iGqv5TI3"
    "kQGUqEiZmroJeZCkYuriZJZXblaHwVIBOTs+wSHww5B6W909mzI07LRKHdPoeFy+3UgUlY4bHBqvPqgR"
    "+kHI8laHnbqLlJKOE3B7s4OpayxO5ijnzaH3hBBs1z2urDST22pAAdEjWZPpcrqPJQp19c/SerO/bw88"
    "PxOhKnfj0z4mqUc1TbBV67Fdc1iYzEb+kf73tabDds2JrlpT36gDvIHKEBx9qAnwwpB2z08MRlNXZ2xj"
    "HkjUKlDoiNr/JkbSBEMgnMS29OSmsCAIcbwAGUrSKZ2zkZUfhnIIu8ukdGpH+CPieHDXD3ltqRa1WdJx"
    "A/YaPXKZFOdm831tTfQN3dXdDrWOqyZtPOhScmo6x8SIFVegJnTX5/WlenRPhRhiiP1IhZEoFvw4OjSk"
    "SxOCdtdneavNwmQmamRf19yqO7S6HnPjdoQ6q0b6QXjAxAGVhyf+QtOILvLo027DoZgxsS0d2zI4MZXb"
    "JyCEyr8TLYsgVKq+RInI8/NFxooWgRw2Ddtdj9WdTtLG/RRrYBu73eE2RwwMIzG8/zbPTten0x1WboJQ"
    "MjaSToxTGZXv+wG7jeG837Ev3PFGDm3Xfjoi7k7NyJWtNh2nTMZSszS2TTb2urheOHzJYSR9D1Ofh4du"
    "OIOwEIK1PTVIcWz1icmcSnYelavEzGA9SU8BIle1QB+Y2bF74jiK91fL7GcbllLiB4JWx+XFqzUq+ZS6"
    "R2IAARFRfYP90oRAj2GLwc6j8q9qAxMz8eTcY6zWEUxSboLtusPabpfT0/lYIFNtuazvdBUKEMRJJDQE"
    "El0MaylxYwaB3lhJ6NcEjbYLEibLKhd3KZ8iG9kV8f4WhDLhkbL6B2yfeA8fMC4Hyz+8hyLy5+icX8hH"
    "l9urVXp7q8N2tcPqVosb6znFpLj9wEjeoly0hrzYYQjlotVHW6IJa6V0xsuZ5OabwXHIRMGVdzNoj4xg"
    "1YTKMbqy1ebkZI7YWlvd7lBteeiRFhgHpGuaUOdnBUlEqJSqHHWuNhZV6lLCwZb5QciNO00ePzmCoSnR"
    "ZkTHLOMF1HPD5JJ6XRNRtsYoEF5EviktdvaphLpHK92q4DCUpEyNRxaLFLMmoTp1SaWQ4luvqGvdVrda"
    "XDpdTESelJL58QyPnypFk62/shX631eawlCSy5g8eWYkyvA83IrCQKrq4xh1JJPiGdzseIShjOIfYK/p"
    "4AYhmlAXs3uBJI1A11SW+hj6F6gMVClTo5Ttu6xdT6qDvgN16UJjebPNTl1doRDvCUmfBCofqlQXU5mG"
    "umlMCHU13c2NFjsNh1xaZ6qS4Yg4+kNJE5BN6+TSRsLghQl1LUK749Lo+Lje8KTKpg3Gi9bh+YIGlrJE"
    "KUqVQopSNnVgz7znNh79lSouDCOIP1Jr/SBMBrHr+JGDTc2o0aKlbjiJOhsGyhBWeJ/qUHzN9OBmrOuC"
    "VtdnebOPtcUIRdySdtfHi1LS6JqgnLcwDY2uE/D6zTrffWOHm+vtYajmHknZgyL6kaRNlQBDohSU/QqR"
    "whKl0nolyc9RNpkqf/hZEuOZu7b37nPuQAH9BOeOF9Lq9bWcibLNzKiK2IxdHYsTmSRBFKibt1z3IMKq"
    "aXBro43jDWQOjjdYoNX1lCof0VRZqepeELJV7bJbd5TyoIl7hlui3iSGbPwThnKfCXBwSBI0fPDn0MEW"
    "STbj/c8fYR0coLucqhADvyHR06INOkahF2QWKdXFuo8uFnG9gLYTUswYXFgoKhgo0or2mi7egZmpUI3t"
    "ustO3WFmNDPkstA0ZRTuNBzGS33l4tETI0gBrhtSKaY4OZ0fSDF6b5xS2pwSwWGoNK7NukOro5I9GZro"
    "X7QYjYbrK6N3vwIkIUFF4t0qlJKO45PS+4sofkATIrmM5G0Ys/dGcYGeH7JVU3fjmZGfaGEyS9rSafcC"
    "ilmD8ZE+3uf6kvXdDvszkibWuaOQjJlRO3GVx6ixF0g2qz3Oz6pVaOiCs3MFCrkUjhNQzJmMFqxEaTmu"
    "10OIQyhZ3e5STfuRrSe5eqdBJ8rIlbFNLGNY4GzWery6VBvuQ6Tyn5jMJc8LAd2ex9WVBmlLH2pTKCFr"
    "qUl939rd3SjW3jZ2u9Q7LqNFteGnTV2thDAyXKNwrhjF2NxzyNqHZVFRA3Rnp4PrjWAaeqShiWSabu45"
    "tHo++azSlGxLZ35MrTpNj+2UAfl/DMWXfThewA+v7CVJFUMJ3a6bTJzJUhrT0AbucYK17S5bVXcYAQ9V"
    "BFTeTjEzmo4QDY1Wz+eNm3XEwAlmgdrrxkppzs3l77on3ROThvor+miwJmCn7rK01qKctxJlwNCESm4R"
    "vyKUwvHmrRrtnk8+YyRLf7B9miZY3+my13QjmymuX8n1rVqP1Z0uFzOpRHwaUWjYME/2GZVH9Ucoxaje"
    "cg48EEhJqWhzajrbf0kqcej6YZLpP3lFSrQoj/j+z7tOgKQfwSQE+L6kkDUPSJXD6J6V1UQpGRCsQqgL"
    "mi7fbrK63ekPqlTLedDCvr7WZGmtlZTVL6z/jK5pNLs+S+vtoXriujqOzxu3qmxUu0PvxXt8fD/eYCjV"
    "kUMQu7Q1FW+Y/Ah1s/PYiM2l0yV1zRBKlGmahqapOD/1M+wON/T+nRSapkVuc4Gma0PPG7qGboh+vMRd"
    "6PiVFA2AH0pEEBKEg9dKq5HTNdiq9Xjpujp6PxFdcBWT6wXc2e3y8rUqzZ6nAh6lOrLoR8BqOMB0ieT6"
    "nSaPLBbJRsh7GKq78wSC25sdXrL3uHS6zNiIFYGuilvru13qbZeT0yooRiaRnQNQBUoCzIyp2EAtAnYH"
    "+2waCug9O5NTh7+kpJRNcXo2vy/vwjAepwmNfNbA0ASzo5l+YvdDng9DyUg2pdp/l8V0LJOEJml1fK6u"
    "NDGEGsx6ZzAdc59urbcJJZyfKzBaTGFoOp4fsFHt8ebtBus73QTqd32FMFimjqZJdhs94pPeuqax13B5"
    "/WaNkawKbtnY6xJKosPKcGWlSRBIzs0VGImS9La6Li9d34vsKYlpalRb8S0xsUBUo2FogsdPFKJUaYcM"
    "iq6ueIuDZiQqILSQO/6ojECQs3VMQ+PRE4VDtdhB0jXtgAP00PYc96UmBDv1Hv/y6lbymRuEyQYNscGp"
    "DL6ltRZb1R7jI5aKL+h4bNYduj0/QYV1TdB1Q7775k6ivbl+mJzo0ITEC0JevLqX1OPLwTBkpVVeWWmw"
    "sddjdEQZtbsNh52aA0iqze3EREjAe2JAVWmHxaPOJslhWCuu1rZ0paEdR5LIayuOLn/w8ajwY0wyIGLS"
    "oCE3SHGYV3cg+axAaTHDpEEUo93sqnizIVtF9APu4zp6+xLa9lenAmtdf3hH6YdLyaSDtZa66loVHEaa"
    "oBgqO764UUSf1ztBX00/hvYrNQ+DpFSr1vFUAvyjyABlSKZMDcvQ9oGAHOTckYaiGiCVvllEkP5ArML+"
    "gof01/1lHjJj9mMoQtUR6x9C0yNDWzK0fAbAmhtrLbZq6pTfQ+fAvVAEr1VbDpOlu9x9Pj+exdSUKHob"
    "iMqRdOz4P2A6hB+HkmTgNMjxGvpPjqK2T4ykGC30I6EOPCallJ4v8cPw7Vxo+XNJh8SJ/GyQVCdN9BgU"
    "3EeRuONIF/N90f56HibzB+u6Wz0/I1JuPyml6uh9MDl9/kv62aX/D7KcCiC2syRWAAAAAElFTkSuQmCC"
)



# ─────────────────────────────────────────────
# SLIP 디코더
# ─────────────────────────────────────────────

SLIP_END     = 0xC0
SLIP_ESC     = 0xDB
SLIP_ESC_END = 0xDC
SLIP_ESC_ESC = 0xDD


def slip_decode(data: bytes) -> list:
    """SLIP 바이너리에서 패킷 목록 추출."""
    packets = []
    current = bytearray()
    i = 0
    while i < len(data):
        b = data[i]
        if b == SLIP_END:
            if current:
                packets.append(bytes(current))
                current = bytearray()
        elif b == SLIP_ESC:
            i += 1
            if i < len(data):
                nb = data[i]
                if nb == SLIP_ESC_END:
                    current.append(SLIP_END)
                elif nb == SLIP_ESC_ESC:
                    current.append(SLIP_ESC)
                else:
                    current.append(nb)
        else:
            current.append(b)
        i += 1
    if current:
        packets.append(bytes(current))
    return packets


# ─────────────────────────────────────────────
# OSC 파서
# ─────────────────────────────────────────────

def _osc_str(data: bytes, offset: int):
    """OSC 문자열 (null 종료, 4바이트 정렬) 읽기."""
    end = data.index(0, offset)
    s = data[offset:end].decode("ascii", errors="replace")
    padded = (end + 4) & ~3
    return s, padded


def _osc_timetag(data: bytes, offset: int):
    """OSC 타임태그 (64비트 고정소수점) → float 초."""
    sec, frac = struct.unpack_from(">II", data, offset)
    return sec + frac / 2**32, offset + 8


def _parse_message(data: bytes, time: float):
    """OSC 메시지 파싱 → {'address', 'time', 'args'}"""
    try:
        address, offset = _osc_str(data, 0)
        if not address.startswith("/"):
            return None

        args = []
        if offset < len(data) and data[offset:offset + 1] == b",":
            type_str, offset = _osc_str(data, offset)
            for t in type_str[1:]:
                if t == "f":
                    args.append(struct.unpack_from(">f", data, offset)[0])
                    offset += 4
                elif t == "i":
                    args.append(struct.unpack_from(">i", data, offset)[0])
                    offset += 4
                elif t == "d":
                    args.append(struct.unpack_from(">d", data, offset)[0])
                    offset += 8
                elif t == "s":
                    val, offset = _osc_str(data, offset)
                    args.append(val)
                elif t == "t":
                    val, offset = _osc_timetag(data, offset)
                    args.append(val)
                elif t in ("T", "F"):
                    args.append(t == "T")
        return {"address": address, "time": time, "args": args}
    except Exception:
        return None


def parse_osc_packet(data: bytes, parent_time: float = 0.0) -> list:
    """OSC 번들 또는 메시지에서 메시지 목록 반환."""
    messages = []
    if data[:8] == b"#bundle\x00":
        try:
            time, offset = _osc_timetag(data, 8)
            while offset + 4 <= len(data):
                size = struct.unpack_from(">I", data, offset)[0]
                offset += 4
                if size == 0 or offset + size > len(data):
                    break
                messages.extend(parse_osc_packet(data[offset:offset + size], time))
                offset += size
        except Exception:
            pass
    else:
        msg = _parse_message(data, parent_time)
        if msg:
            messages.append(msg)
    return messages


# ─────────────────────────────────────────────
# 출력할 OSC 주소와 컬럼 헤더 (순서 유지)
# ─────────────────────────────────────────────

GPS_ADDRESS = "/gps"
NMEA_ADDRESS = "/auxserial"


def _nmea_to_decimal(value: str, direction: str) -> float | None:
    """NMEA ddmm.mmmm 형식 → 십진수 위/경도 변환."""
    try:
        v = float(value)
        degrees = int(v / 100)
        minutes = v % 100
        decimal = degrees + minutes / 60.0
        if direction in ("S", "W"):
            decimal = -decimal
        return decimal
    except (ValueError, TypeError):
        return None


def _extract_gps_from_nmea(auxserial_msgs: list) -> list:
    """
    /auxserial 메시지에서 NMEA GPS 위도/경도/고도 추출.
    args[0] = 완전한 NMEA 문자열 (예: '$GNRMC,055301.00,A,3723.12,N,12658.34,E,...\r\n')
    반환 args = [lat, lon, alt_or_None]
    """
    gps_msgs = []
    for msg in auxserial_msgs:
        args = msg.get("args", [])
        if not args or not isinstance(args[0], str):
            continue
        sentence = args[0].strip()
        if "*" in sentence:
            sentence = sentence[:sentence.index("*")]
        fields = sentence.split(",")
        if not fields:
            continue
        tag = fields[0].upper()

        # $GPRMC / $GNRMC: 위도/경도만 있음, 고도 없음
        if tag in ("$GPRMC", "$GNRMC") and len(fields) >= 7:
            if fields[2].upper() != "A":
                continue
            lat = _nmea_to_decimal(fields[3], fields[4].upper())
            lon = _nmea_to_decimal(fields[5], fields[6].upper())
            if lat is not None and lon is not None:
                gps_msgs.append({"time": msg["time"], "args": [lat, lon, None]})

        # $GPGGA / $GNGGA: 위도/경도 + 고도(fields[9], MSL m)
        elif tag in ("$GPGGA", "$GNGGA") and len(fields) >= 10:
            if fields[6] == "0":
                continue
            lat = _nmea_to_decimal(fields[2], fields[3].upper())
            lon = _nmea_to_decimal(fields[4], fields[5].upper())
            try:
                alt = float(fields[9]) if fields[9] else None
            except ValueError:
                alt = None
            if lat is not None and lon is not None:
                gps_msgs.append({"time": msg["time"], "args": [lat, lon, alt]})

    return gps_msgs

WANTED_ADDRESSES = {
    "/humidity":    ["Humidity (%)"],
    "/quaternion":  ["W", "X", "Y", "Z"],
    "/sensors":     ["Gyro X (deg/s)", "Gyro Y (deg/s)", "Gyro Z (deg/s)",
                     "Accel X (g)",   "Accel Y (g)",    "Accel Z (g)",
                     "Mag X (uT)",    "Mag Y (uT)",     "Mag Z (uT)"],
    "/temperature": ["Temperature (°C)"],
}


def seconds_to_hhmmss(t: float) -> str:
    total_s = int(abs(t))
    h = total_s // 3600
    m = (total_s % 3600) // 60
    s = total_s % 60
    sign = "-" if t < 0 else ""
    return f"{sign}{h:02d}:{m:02d}:{s:02d}"


def seconds_to_ms(t: float) -> str:
    """초 → ms 정수 문자열."""
    return str(round(t * 1000))


# ─────────────────────────────────────────────
# 변환 로직
# ─────────────────────────────────────────────

def _find_closest(msgs: list, t: float):
    """
    시각 t에 가장 가까운 메시지 args 반환.
    이진 탐색으로 O(log n) 처리.
    """
    if not msgs:
        return None
    lo, hi = 0, len(msgs) - 1
    while lo < hi:
        mid = (lo + hi) // 2
        if msgs[mid]["time"] < t:
            lo = mid + 1
        else:
            hi = mid
    candidates = [lo]
    if lo > 0:
        candidates.append(lo - 1)
    best = min(candidates, key=lambda i: abs(msgs[i]["time"] - t))
    return msgs[best]["args"]


def _forward_fill(msgs: list, t: float):
    """시각 t 이하의 가장 최근 메시지 args 반환 (이진 탐색)."""
    lo, hi, result = 0, len(msgs) - 1, None
    while lo <= hi:
        mid = (lo + hi) // 2
        if msgs[mid]["time"] <= t:
            result = msgs[mid]["args"]
            lo = mid + 1
        else:
            hi = mid - 1
    return result


def _fmt_time(t: float, fmt: str) -> str:
    return seconds_to_ms(t) if fmt == "tick_ms" else seconds_to_hhmmss(t)


def convert_xio(xio_path: Path, dest_dir: Path, log, opts: dict):
    """XIO 바이너리 파일 → 통합 CSV 1개."""
    raw = xio_path.read_bytes()
    log(f"  파일 크기: {len(raw):,} bytes")

    packets = slip_decode(raw)
    log(f"  SLIP 패킷 수: {len(packets):,}")

    # 주소별 메시지 수집 후 시간순 정렬
    by_address = defaultdict(list)
    for pkt in packets:
        for msg in parse_osc_packet(pkt):
            by_address[msg["address"]].append(msg)
    for addr in by_address:
        by_address[addr].sort(key=lambda m: m["time"])

    if not by_address:
        log("  [경고] 파싱된 데이터가 없습니다.")
        return 0

    # NTP 절대시각 → 녹화 시작 기준 상대시각 정규화
    valid_times = [m["time"] for msgs in by_address.values() for m in msgs if m["time"] > 0]
    t0 = min(valid_times) if valid_times else 0.0
    if t0 > 0:
        for msgs in by_address.values():
            for m in msgs:
                if m["time"] > 0:
                    m["time"] -= t0
    log(f"  시작 시각 기준 정규화 완료 (t0 = {t0:.2f}s)")
    log(f"  파일 내 전체 주소: {', '.join(sorted(by_address.keys()))}")

    # ms 단위 시간값 존재 여부 확인
    has_ms_precision = any(
        (m["time"] % 1.0) != 0.0
        for msgs in by_address.values() for m in msgs if m["time"] > 0
    )
    log(f"  ms 단위 시간값: {'있음' if has_ms_precision else '없음 (초 단위만)'}")

    # GPS 확인 (네이티브 /gps → 없으면 /auxserial/string NMEA 파싱)
    gps_msgs = by_address.get(GPS_ADDRESS, [])
    if gps_msgs:
        log(f"  GPS ({GPS_ADDRESS}): {len(gps_msgs):,}개")
    else:
        auxserial_msgs = by_address.get(NMEA_ADDRESS, [])
        if auxserial_msgs:
            gps_msgs = _extract_gps_from_nmea(auxserial_msgs)
            if gps_msgs:
                log(f"  GPS (NMEA via {NMEA_ADDRESS}): {len(gps_msgs):,}개 파싱됨")
            else:
                log(f"  [경고] {NMEA_ADDRESS} 에서 유효한 NMEA GPS 문장 없음")
        else:
            log(f"  [경고] GPS 데이터 없음 ({GPS_ADDRESS}, {NMEA_ADDRESS} 모두 없음)")

    for addr, cols in WANTED_ADDRESSES.items():
        n = len(by_address.get(addr, []))
        log(f"  {addr}: {n:,}개" if n else f"  [없음] {addr}")

    # 옵션 파싱
    time_fmt      = opts.get("time_format", "hhmmss")   # "hhmmss" | "tick_ms"
    save_hz       = opts.get("save_hz", 0.0)
    use_period    = save_hz > 0
    enabled_ch    = opts.get("enabled_channels", set(WANTED_ADDRESSES.keys()) | {GPS_ADDRESS})
    encoding      = "utf-8-sig" if opts.get("utf8bom", True) else "utf-8"

    # 활성화된 센서 컬럼 구성
    col_specs = [
        (addr, cols)
        for addr, cols in WANTED_ADDRESSES.items()
        if addr in by_address and addr in enabled_ch
    ]
    has_gps = bool(gps_msgs) and (GPS_ADDRESS in enabled_ch)
    gps_col_enabled = GPS_ADDRESS in enabled_ch  # 체크박스 켜짐 여부

    # 시간 헤더
    time_header = "Time (ms)" if time_fmt == "tick_ms" else "Time (HH:MM:SS)"
    gps_headers = ["Latitude", "Longitude", "Altitude (m)"] if gps_col_enabled else []
    headers = [time_header] + gps_headers + [c for _, cols in col_specs for c in cols]

    # 출력 파일명: 시간 형식 + 저장 주기 포함 (중복 방지)
    fmt_tag = "ms" if time_fmt == "tick_ms" else "hhmmss"
    hz_tag  = f"_{save_hz:g}Hz" if use_period else ""
    # 채널 약어 (전체 선택 시 태그 없음, 일부만 선택 시 약어 나열)
    ALL_CH = {GPS_ADDRESS} | set(WANTED_ADDRESSES.keys())
    CH_ABBR = {
        GPS_ADDRESS:    "gps",
        "/sensors":     "sen",
        "/quaternion":  "quat",
        "/humidity":    "hum",
        "/temperature": "temp",
    }
    CH_ORDER = [GPS_ADDRESS, "/sensors", "/quaternion", "/humidity", "/temperature"]
    if enabled_ch >= ALL_CH:
        ch_tag = ""
    else:
        ch_tag = "_" + "-".join(CH_ABBR[a] for a in CH_ORDER if a in enabled_ch)
    out_path = dest_dir / f"{xio_path.stem}_{fmt_tag}{hz_tag}{ch_tag}.csv"

    # ── 타임라인 결정 ───────────────────────────
    # HH:MM:SS 형식은 초 단위 해상도 → Hz 미설정이어도 1Hz 최근접값 사용
    if use_period or time_fmt == "hhmmss":
        period = 1.0 / save_hz if use_period else 1.0
        t_max = max(m["time"] for msgs in by_address.values() for m in msgs if m["time"] > 0)
        n_steps = int(t_max / period) + 1
        if use_period:
            log(f"  저장 주기: {save_hz}Hz  간격: {period*1000:.1f}ms  총 {n_steps}행")
        else:
            log(f"  HH:MM:SS 형식 → 1Hz 자동 적용  총 {n_steps}행")
        with open(out_path, "w", newline="", encoding=encoding) as f:
            writer = csv.writer(f)
            writer.writerow(headers)

            last_alt = ""
            for i in range(n_steps):
                t = i * period
                row = [_fmt_time(t, time_fmt)]

                # GPS
                if gps_col_enabled:
                    if has_gps:
                        args = _forward_fill(gps_msgs, t)
                        if args and len(args) >= 2:
                            if len(args) >= 3 and args[2] is not None:
                                last_alt = f"{args[2]:.2f}"
                            row += [f"{args[0]:.7f}", f"{args[1]:.7f}", last_alt]
                        else:
                            row += ["", "", ""]
                    else:
                        row += ["", "", ""]

                # 센서
                for addr, cols in col_specs:
                    args = _find_closest(by_address[addr], t) or []
                    row += [str(args[k]) if k < len(args) else "" for k in range(len(cols))]

                writer.writerow(row)

        log(f"  ✓ {out_path.name}  ({n_steps:,}행, {len(headers)}개 컬럼)")
        return 1

    else:
        # 원시 타임라인: GPS 또는 가장 많은 센서 기준 + forward-fill
        if has_gps:
            primary = gps_msgs
            primary_is_gps = True
        else:
            available = {a: by_address[a] for a in WANTED_ADDRESSES
                         if a in by_address and a in enabled_ch}
            if not available:
                log("  [경고] 사용 가능한 데이터가 없습니다.")
                return 0
            primary_addr = max(available, key=lambda a: len(available[a]))
            primary = available[primary_addr]
            primary_is_gps = False
            log(f"  {primary_addr}를 주 타임라인으로 사용")

        with open(out_path, "w", newline="", encoding=encoding) as f:
            writer = csv.writer(f)
            writer.writerow(headers)

            last_alt = ""
            for msg in primary:
                t = msg["time"]
                row = [_fmt_time(t, time_fmt)]

                # GPS
                if gps_col_enabled:
                    if has_gps:
                        if primary_is_gps and len(msg["args"]) >= 2:
                            a = msg["args"]
                            if len(a) >= 3 and a[2] is not None:
                                last_alt = f"{a[2]:.2f}"
                            row += [f"{a[0]:.7f}", f"{a[1]:.7f}", last_alt]
                        else:
                            args = _forward_fill(gps_msgs, t)
                            if args and len(args) >= 2:
                                if len(args) >= 3 and args[2] is not None:
                                    last_alt = f"{args[2]:.2f}"
                                row += [f"{args[0]:.7f}", f"{args[1]:.7f}", last_alt]
                            else:
                                row += ["", "", ""]
                    else:
                        row += ["", "", ""]

                # 센서 (forward-fill)
                for addr, cols in col_specs:
                    args = _forward_fill(by_address[addr], t) or []
                    row += [str(args[k]) if k < len(args) else "" for k in range(len(cols))]

                writer.writerow(row)

        log(f"  ✓ {out_path.name}  ({len(primary):,}행, {len(headers)}개 컬럼)")
        return 1


def run_conversion(input_paths: list, dest_dir: Path, log, on_done, opts: dict):
    try:
        total = 0
        for p in input_paths:
            p = Path(p)
            log(f"\n▶ {p.name} 처리 중...")
            if not p.is_file():
                log("  [오류] 파일이 아닙니다.")
                continue
            if p.suffix.upper() != ".XIO":
                log(f"  [오류] .XIO 파일이 아닙니다: {p.suffix}")
                continue
            n = convert_xio(p, dest_dir, log, opts)
            total += n
        on_done(total)
    except Exception as e:
        log(f"\n[오류] {e}")
        import traceback
        log(traceback.format_exc())
        on_done(0)


# ─────────────────────────────────────────────
# GUI
# ─────────────────────────────────────────────

PLACEHOLDER = "Select SD card file(s)"


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("NGIMU XIO to CSV Converter v1.0")
        self.resizable(True, False)
        # 아이콘 적용 (내장 base64 → 임시 파일 → iconbitmap)
        try:
            import base64, tempfile, os
            ico_data = base64.b64decode(YONGBEE_ICON_B64)
            tmp = tempfile.NamedTemporaryFile(suffix='.ico', delete=False)
            tmp.write(ico_data)
            tmp.close()
            self.iconbitmap(tmp.name)
            self.after(500, lambda: os.unlink(tmp.name))
        except Exception:
            pass
        self._input_paths = []
        self._build_ui()
        self._center()

    def _center(self):
        self.update_idletasks()
        w, h = self.winfo_width(), self.winfo_height()
        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()
        self.geometry(f"+{(sw-w)//2}+{(sh-h)//2}")

    def _build_ui(self):
        self.columnconfigure(0, weight=1)
        P = {"padx": 8, "pady": 3}

        # ── Input / Output ──────────────────────────
        io_frame = tk.LabelFrame(self, text="Input / Output", padx=6, pady=4)
        io_frame.grid(row=0, column=0, sticky="ew", padx=10, pady=(10, 4))
        io_frame.columnconfigure(1, weight=1)

        tk.Label(io_frame, text="SD Card File(s):").grid(row=0, column=0, sticky="e", **P)
        self.files_var = tk.StringVar()
        self.files_entry = tk.Entry(
            io_frame, textvariable=self.files_var, width=55, fg="grey",
            relief="flat", highlightthickness=1,
            highlightbackground="#aaa", highlightcolor="#0078d4")
        self.files_entry.insert(0, PLACEHOLDER)
        self.files_entry.bind("<FocusIn>", self._clear_ph)
        self.files_entry.grid(row=0, column=1, sticky="ew", **P)
        tk.Button(io_frame, text="...", width=3,
                  command=self._browse_files).grid(row=0, column=2, **P)

        tk.Label(io_frame, text="Destination Directory:").grid(row=1, column=0, sticky="e", **P)
        self.dest_var = tk.StringVar(value=str(Path.home() / "Desktop"))
        tk.Entry(
            io_frame, textvariable=self.dest_var, width=55,
            relief="flat", highlightthickness=1,
            highlightbackground="#aaa", highlightcolor="#0078d4"
        ).grid(row=1, column=1, sticky="ew", **P)
        tk.Button(io_frame, text="...", width=3,
                  command=self._browse_dest).grid(row=1, column=2, **P)

        # ── Save Options (스크롤 가능) ──────────────
        opts_outer = tk.LabelFrame(self, text="Save Options", padx=6, pady=4)
        opts_outer.grid(row=1, column=0, sticky="ew", padx=10, pady=4)
        opts_outer.columnconfigure(0, weight=1)

        canvas = tk.Canvas(opts_outer, height=240, highlightthickness=0)
        vsb = tk.Scrollbar(opts_outer, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)
        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)

        self.opts_frame = tk.Frame(canvas)
        self.opts_frame.columnconfigure(0, weight=1)
        win_id = canvas.create_window((0, 0), window=self.opts_frame, anchor="nw")

        self.opts_frame.bind("<Configure>",
                             lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
        canvas.bind("<Configure>",
                    lambda e: canvas.itemconfig(win_id, width=e.width))
        # 마우스 휠 스크롤
        canvas.bind("<MouseWheel>",
                    lambda e: canvas.yview_scroll(-1 * (e.delta // 120), "units"))

        self._build_options(self.opts_frame)

        # ── Convert 버튼 ────────────────────────────
        btn_frame = tk.Frame(self)
        btn_frame.grid(row=2, column=0, sticky="e", padx=10, pady=4)
        self.convert_btn = tk.Button(btn_frame, text="Convert", width=14,
                                     command=self._start)
        self.convert_btn.pack()

        # ── 로그창 ──────────────────────────────────
        self.log_frame = tk.Frame(self)
        self.log_frame.grid(row=3, column=0, sticky="nsew", padx=10, pady=(0, 4))
        self.log_frame.grid_remove()
        self.log_text = tk.Text(
            self.log_frame, width=72, height=14, state="disabled",
            relief="flat", bg="#1e1e1e", fg="#d4d4d4",
            font=("Consolas", 9), wrap="word")
        self.log_text.pack(side="left", fill="both", expand=True)
        sb = tk.Scrollbar(self.log_frame, command=self.log_text.yview)
        sb.pack(side="right", fill="y")
        self.log_text.config(yscrollcommand=sb.set)

        # ── 진행바 ──────────────────────────────────
        self.progress = ttk.Progressbar(self, mode="indeterminate", length=500)
        self.progress.grid(row=4, column=0, padx=10, pady=(0, 8), sticky="ew")
        self.progress.grid_remove()

    # ────────────────────────────────────────────
    # 옵션 패널 구성 (항목 추가/수정 용이하도록 섹션별 분리)
    # ────────────────────────────────────────────

    def _build_options(self, parent):
        P = {"padx": 6, "pady": 2}
        r = 0

        # ── 섹션 1: 시간 형식 ────────────────────
        tf = tk.LabelFrame(parent, text="Time Format", padx=6, pady=4)
        tf.grid(row=r, column=0, sticky="ew", padx=4, pady=(4, 2))
        tf.columnconfigure(2, weight=1)
        r += 1

        self.time_fmt_var = tk.StringVar(value="hhmmss")
        tk.Radiobutton(tf, text="HH:MM:SS  (시:분:초)",
                       variable=self.time_fmt_var, value="hhmmss").grid(
                       row=0, column=0, sticky="w", padx=10)
        tk.Radiobutton(tf, text="Tick (ms)  (밀리초 정수)",
                       variable=self.time_fmt_var, value="tick_ms").grid(
                       row=0, column=1, sticky="w", padx=10)

        # ── 섹션 2: 저장 주기 ────────────────────
        pf = tk.LabelFrame(parent, text="Save Period", padx=6, pady=4)
        pf.grid(row=r, column=0, sticky="ew", padx=4, pady=2)
        pf.columnconfigure(3, weight=1)
        r += 1

        self.use_period_var = tk.BooleanVar(value=False)
        tk.Checkbutton(pf, text="고정 주기 활성화:",
                       variable=self.use_period_var,
                       command=self._on_period_toggle).grid(
                       row=0, column=0, sticky="w")

        self.hz_var = tk.StringVar(value="1")
        self.hz_entry = tk.Entry(pf, textvariable=self.hz_var, width=8,
                                 state="disabled", relief="flat",
                                 highlightthickness=1, highlightbackground="#aaa")
        self.hz_entry.grid(row=0, column=1, padx=4)
        tk.Label(pf, text="Hz").grid(row=0, column=2, sticky="w")

        self.period_info_lbl = tk.Label(pf, text="", fg="grey", font=("Arial", 8))
        self.period_info_lbl.grid(row=1, column=0, columnspan=4, sticky="w", pady=(0, 2))

        self.hz_var.trace_add("write", self._update_period_info)
        self._on_period_toggle()

        # ── 섹션 3: 데이터 채널 선택 ─────────────
        cf = tk.LabelFrame(parent, text="Data Channels", padx=6, pady=4)
        cf.grid(row=r, column=0, sticky="ew", padx=4, pady=2)
        r += 1

        CHANNELS = [
            (GPS_ADDRESS,    "GPS (Lat / Lon)"),
            ("/sensors",     "Sensors  (Gyro / Accel / Mag)"),
            ("/quaternion",  "Quaternion  (W / X / Y / Z)"),
            ("/humidity",    "Humidity"),
            ("/temperature", "Temperature"),
        ]
        self.ch_vars = {}
        for idx, (addr, label) in enumerate(CHANNELS):
            v = tk.BooleanVar(value=True)
            self.ch_vars[addr] = v
            tk.Checkbutton(cf, text=label, variable=v).grid(
                row=idx // 2, column=idx % 2, sticky="w", padx=10, pady=1)

        # ── 섹션 4: 출력 옵션 ────────────────────
        of = tk.LabelFrame(parent, text="Output Options", padx=6, pady=4)
        of.grid(row=r, column=0, sticky="ew", padx=4, pady=(2, 6))
        r += 1

        self.utf8bom_var = tk.BooleanVar(value=True)
        tk.Checkbutton(of, text="UTF-8 BOM 포함  (Excel 한글 호환)",
                       variable=self.utf8bom_var).grid(
                       row=0, column=0, sticky="w", padx=10)

        self.open_after_var = tk.BooleanVar(value=False)
        tk.Checkbutton(of, text="변환 완료 후 출력 폴더 열기",
                       variable=self.open_after_var).grid(
                       row=0, column=1, sticky="w", padx=10)

    # ────────────────────────────────────────────
    # 콜백
    # ────────────────────────────────────────────

    def _on_period_toggle(self):
        if self.use_period_var.get():
            self.hz_entry.config(state="normal")
            self._update_period_info()
        else:
            self.hz_entry.config(state="disabled")
            self.period_info_lbl.config(
                text="주기 미설정: 원시 데이터 타임라인 사용 (GPS 또는 최다 센서 기준)",
                fg="grey")

    def _update_period_info(self, *_):
        if not self.use_period_var.get():
            return
        try:
            hz = float(self.hz_var.get())
            if hz <= 0:
                raise ValueError
            ms = 1000.0 / hz
            self.period_info_lbl.config(
                text=f"간격 {ms:.2f} ms → 초당 최대 {hz:.0f}개 저장  "
                     f"(평균 없음, 해당 시각에 가장 가까운 값 1개 사용)",
                fg="#0055aa")
        except ValueError:
            self.period_info_lbl.config(text="Hz 값이 올바르지 않습니다.", fg="red")

    def _get_opts(self) -> dict:
        opts = {
            "time_format":      self.time_fmt_var.get(),
            "save_hz":          0.0,
            "enabled_channels": {addr for addr, v in self.ch_vars.items() if v.get()},
            "utf8bom":          self.utf8bom_var.get(),
            "open_after":       self.open_after_var.get(),
        }
        if self.use_period_var.get():
            try:
                hz = float(self.hz_var.get())
                if hz > 0:
                    opts["save_hz"] = hz
            except ValueError:
                pass
        return opts

    def _clear_ph(self, _):
        if self.files_entry.get() == PLACEHOLDER:
            self.files_entry.delete(0, "end")
            self.files_entry.config(fg="black")

    def _browse_files(self):
        paths = filedialog.askopenfilenames(
            title="XIO 파일 선택",
            filetypes=[("XIO files", "*.xio *.XIO"), ("All files", "*.*")])
        if paths:
            self._input_paths = list(paths)
            self.files_entry.config(fg="black")
            self.files_var.set("; ".join(Path(p).name for p in paths))

    def _browse_dest(self):
        p = filedialog.askdirectory(title="출력 폴더 선택")
        if p:
            self.dest_var.set(p)

    def _log(self, msg: str):
        def _do():
            self.log_text.config(state="normal")
            self.log_text.insert("end", msg + "\n")
            self.log_text.see("end")
            self.log_text.config(state="disabled")
        self.after(0, _do)

    def _start(self):
        paths = self._input_paths or []
        if not paths:
            raw = self.files_var.get().strip()
            if raw and raw != PLACEHOLDER:
                paths = [p.strip() for p in raw.split(";") if p.strip()]
        if not paths:
            messagebox.showwarning("입력 없음", "XIO 파일을 선택하세요.")
            return

        dest = self.dest_var.get().strip()
        if not dest:
            messagebox.showwarning("출력 없음", "Destination Directory를 선택하세요.")
            return

        opts = self._get_opts()
        if self.use_period_var.get() and opts["save_hz"] == 0.0:
            messagebox.showwarning("주기 오류", "저장 주기(Hz)를 올바르게 입력하세요.")
            return

        dest_path = Path(dest)
        dest_path.mkdir(parents=True, exist_ok=True)

        self.convert_btn.config(state="disabled")
        self.log_frame.grid()
        self.progress.grid()
        self.progress.start(10)
        self.log_text.config(state="normal")
        self.log_text.delete("1.0", "end")
        self.log_text.config(state="disabled")

        self._log(f"변환 시작 | 파일 수: {len(paths)}")
        self._log(f"출력 경로: {dest_path}")
        self._log(f"시간 형식: {'Tick (ms)' if opts['time_format'] == 'tick_ms' else 'HH:MM:SS'}")
        if opts["save_hz"] > 0:
            self._log(f"저장 주기: {opts['save_hz']}Hz  ({1000/opts['save_hz']:.2f}ms 간격, 최근접값)")
        else:
            self._log("저장 주기: 원시 타임라인 사용")

        def on_done(total):
            def _finish():
                self.progress.stop()
                self.progress.grid_remove()
                self.convert_btn.config(state="normal")
                if total > 0:
                    self._log(f"\n완료! CSV 파일 {total}개 생성됨.")
                    messagebox.showinfo("완료",
                        f"CSV {total}개 파일 생성 완료!\n\n출력 위치:\n{dest_path}")
                    if opts.get("open_after") and sys.platform == "win32":
                        os.startfile(dest_path)
                else:
                    self._log("\n변환된 파일이 없습니다.")
                    messagebox.showwarning("결과 없음", "변환된 데이터가 없습니다.")
            self.after(0, _finish)

        threading.Thread(
            target=run_conversion,
            args=(paths, dest_path, self._log, on_done, opts),
            daemon=True
        ).start()


if __name__ == "__main__":
    App().mainloop()
